Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-09, with the labels that each got.

#858 Tall cheese: rebuild current user
  package.json
  shrinkwrap.yaml
  src/app.js
  src/components/banners/super-user.js
  src/components/header/index.js
  src/components/user-options-pop/index.js
  src/state/current-user.js
  src/state/handler-middleware.js
  src/state/local-storage.js
  src/state/store.js
  src/utils/run-latest.js
Labels: Under Review

#869 Lean-exception: remove storybook & gitignore package.json
  .gitignore
  package-lock.json
  package.json
  server/redirects.js
  src/components/buttons/story.js
  src/components/collections-list/story.js
  src/components/containers/profile/story.js
  src/components/deleted-projects/story.js
  src/components/header/story.js
  src/components/images/story.js
  src/components/new-stuff/story.js
  src/components/overlays/story.js
  src/components/profile-list/story.js
  src/components/questions/story.js
  src/components/search-form/story.js
  stories/data.js
  stories/index.js
  stories/inputs.js
  stories/util.js
  storybook-config/.babelrc
  storybook-config/config.js
  storybook-config/preview-head.html
  storybook-config/webpack.config.js
Labels: Ready to merge

#833 Eggplant persimmon: Trying to fix stale data bugs around projects and collections
  shrinkwrap.yaml
  src/components/collections-list/index.js
  src/components/project/project-item.js
  src/state/api.js
  src/state/collection.js
  src/state/current-user.js
  src/state/project-options.js
  src/state/user.js
Labels: Ready to merge

#842 Profuse tea: AB testing with a very basic test on the secret page
  server/ab-tests.js
  server/render.js
  server/routes.js
  shared/ab-tests.js
  src/client.js
  src/presenters/pages/secret.js
  src/presenters/pages/secret.styl
  src/server.js
  src/state/ab-tests.js
  src/state/current-user.js
  src/state/globals.js
  views/index.ejs
Labels: Ready to merge

#862 honored-cantaloupe: don't let nonadmins see delete project button from the project page
  src/presenters/pages/project.js
Labels: Ready to merge

#859 Probable castanet: Use larger font on touch devices to prevent strange zoom behavior
  src/components/inputs/text-input.styl
Labels: Ready to merge

#873 Acidic-tomate: standardize error handling on image upload failures
  src/components/team-analytics/team-analytics-activity.js
  src/state/error-handlers.js
  src/state/project.js
  src/state/team.js
  src/state/uploader.js
  src/state/user.js
Labels: Ready to merge

#881 Judicious vase: replace toggleBookmark with a hook
  src/components/project/featured-project.js
  src/presenters/pages/project.js
  src/state/collection.js
Labels: Waiting on Reviews

#882 Caterwauling freighter: useSample hook
  src/components/collection/container.js
  src/components/collections-list/more-collections.js
  src/components/related-projects/index.js
  src/hooks/use-sample.js
  src/presenters/pages/create.js
Labels: Ready to merge

#875 Quixotic rocket: SSR transpile on startup, indicate initial vs retranspile
  README.md
  server/render.js
Labels: Ready to merge

#854 hickory-zircon: Mark shared component
  shrinkwrap.yaml
  src/components/mark/index.js
  src/components/mark/styles.styl
  src/presenters/pages/create.js
  src/presenters/pages/create.styl
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#880 Add support for Jest in Circle CI
  .circleci/config.yml
  package.json
  test/index.js
Labels: Under Review

#866 Curvy-bandicoot: maintain same page if a project or collection gets deleted
  src/client.js
  src/components/pagination-controller/index.js
Labels: Under Review

#894 Ash straw: remove slack login
  src/components/buttons/sign-in-button.js
  src/components/layout/sign-in-layout.js
  src/components/sign-in-pop/index.js
  src/presenters/pages/login.js
  src/presenters/pages/router.js
  src/state/dev-toggles.js
Labels: Ready to merge

#893 Verbose spider: update/replace 3rd-party components to clean up React errors
  package.json
  server/render.js
  shrinkwrap.yaml
  src/app.js
  src/components/layout/index.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/error.js
  src/presenters/pages/project.js
  src/presenters/pages/pupdates-preview.js
  src/presenters/pages/questions.js
  src/presenters/pages/search.js
  src/presenters/pages/secret.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/server.js
Labels: Ready to merge

#891 Sudsy balance: Avatar component
  src/components/collection/create-collection-pop.styl
  src/components/images/avatar.js
  src/components/images/avatar.styl
  src/components/profile-list/index.js
Labels: Ready to merge

#888 Historical salesman: Badge shared component
  src/components/badges/badge.js
  src/components/badges/badge.styl
  src/components/constants.styl
  src/components/project/add-project-to-collection-pop.js
  src/components/project/popover.styl
  src/components/project/project-item-small.js
  src/components/project/project-item.styl
  src/components/search-results/index.js
Labels: Ready to merge

#892 Sumptuous rainbow: styled components SSR, render '→' as icon
  .babelrc
  package.json
  server/render.js
  server/routes.js
  shrinkwrap.yaml
  src/components/arrow/index.js
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/home-v2/banner.styl
  views/index.ejs
Labels: Waiting on Reviews

#900 repeated-snapper: add Norton SafeWeb verification
  views/index.ejs
Labels: Waiting on Reviews

#901 repeated-snapper: Remove norton verification metatag
  views/index.ejs
Labels: Waiting on Reviews

#896 Decisive kilometer: fix button text on join/leave
  src/models/project.js
  src/presenters/pages/project.js
  src/state/project-options.js
Labels: Ready to merge

#899 Fixed Homepage Banner Text COlors
  src/presenters/pages/home-v2/banner.js
Labels: Ready to merge

#903 Search results styling
  src/components/search-results/index.js
  src/components/search-results/search-results.styl
Labels: Ready to merge

#905 Quixotic rocket: Change your ab test group from the secret page
  src/client.js
  src/presenters/pages/secret.js
  src/presenters/pages/secret.styl
  src/server.js
  src/state/ab-tests.js
  src/state/globals.js
Labels: Ready to merge

#908 Marmalade tarantula: VisuallyHidden component
  src/components/collection/collection-result-item.js
  src/components/containers/visually-hidden.js
  src/components/global.styl
  src/components/inputs/text-input.js
  src/components/popover/index.js
  src/presenters/pages/secret.js
Labels: Ready to merge

#907 Astonishing speedwell: AnimationContainer component
  src/components/animation-container/animations.styl
  src/components/animation-container/index.js
  src/components/collection/collection-item.js
  src/components/deleted-projects/index.js
  src/components/project/featured-project.js
  src/components/project/project-item.js
Labels: Ready to merge

#902 Lacy gondola: Private icon
  src/components/private-badge/index.js
  src/components/private-badge/styles.styl
  src/components/project/project-item.js
  src/components/project/project-item.styl
Labels: Ready to merge

#836 chestnut-headphones: Add onboarding banner to homepage and profile page
  .glitch-assets
  package.json
  shared/ab-tests.js
  shrinkwrap.yaml
  src/components/categories-grid/index.js
  src/components/categories-grid/styles.styl
  src/components/constants.styl
  src/components/header/index.js
  src/components/images/emoji.js
  src/components/new-project-pop/index.js
  src/components/new-project-pop/styles.styl
  src/components/onboarding-banner/illustration.js
  src/components/onboarding-banner/illustration.styl
  src/components/onboarding-banner/index.js
  src/components/onboarding-banner/styles.styl
  src/presenters/pages/create.js
  src/presenters/pages/create.styl
  src/presenters/pages/home-v2/banner.styl
  src/presenters/pages/home-v2/constants.styl
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/home-v2/styles.styl
  src/presenters/pages/user.js
  styles/globals.styl
Labels: Ready to merge

#897 🌪🌈 Complete Farmhouse: replace Arrow with Icon
  src/components/arrow/index.js
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/collections-list/more-collections.js
  src/components/collections-list/styles.styl
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/new-stuff/new-stuff-article.js
  src/components/new-stuff/new-stuff-article.styl
  src/components/questions/index.js
  src/components/questions/questions.styl
  src/components/recent-projects/index.js
  src/components/recent-projects/styles.styl
  src/components/related-projects/index.js
  src/components/related-projects/styles.styl
  src/components/search-form/autocomplete.js
  src/components/search-form/autocomplete.styl
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/home-v2/banner.styl
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#909 Nova chance: cta edit project button, fix anon user avatars
  src/components/images/avatar.js
  src/components/project/project-actions.js
Labels: Ready to merge

#890 Jasper reward: React.memo Markdown component
  src/components/text/markdown.js
Labels: Under Review

#911 Fallacious slice: Remove the global stylesheet
  server/routes.js
  src/components/collection/collection-item.styl
  src/components/containers/results-list.styl
  src/components/deleted-projects/deleted-projects.styl
  src/components/global.styl
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
  src/components/link/wrapping-link.js
  src/components/link/wrapping-link.styl
  src/components/new-project-pop/styles.styl
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/components/team-analytics/styles.styl
  src/components/team-analytics/team-analytics-project-pop.js
  src/components/user-options-pop/index.js
  src/components/user-options-pop/styles.styl
  styles/c3.styl
  styles/globals.styl
  styles/icons.styl
  styles/styles.styl
  webpack.config.js
Labels: Under Review

#874 Superb guide: Clean up the standard data loading code and move it to shared
  shared/api-loaders.js
  src/components/project/project-item.js
  src/models/team.js
  src/presenters/pages/collection.js
  src/presenters/pages/team-or-user.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/state/api-cache.js
  src/state/collection.js
  src/state/project-options.js
  src/state/project.js
  src/state/team.js
  src/state/user.js
Labels: Waiting on Reviews

#912 Create account page
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
Labels: Under Review

#910 User Options Pop Button Wrap & Top Search Result Vertical Alignment
  src/components/images/avatar.styl
  src/components/search-results/index.js
  src/components/search-results/search-results.styl
  src/components/user-options-pop/styles.styl
Labels: Ready to merge

#852 green-impatiens: Handle Magic Link
  package.json
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
  src/components/sign-in/get-magic-code.js
  src/components/sign-in/styles.styl
  src/components/sign-in/use-magic-code.js
  src/presenters/pages/login/callbacks.js
  src/presenters/pages/login/index.js
  src/presenters/pages/login/reset-password.js
  src/presenters/pages/login/reset-password.styl
  src/presenters/pages/router.js
Labels: Ready to merge

#924 Fallacious slice: Fix the site in Edge
  .babelrc.client.json
  webpack.config.js
Labels: Waiting on Reviews

#927 Shocking panther: replace support link with help center link
  src/components/user-options-pop/index.js
Labels: Waiting on Reviews

#928 Fast bottom: redirect `/~:domain/edit` to editor, `/~:domain/console` to console
  server/routes.js
Labels: Ready to merge

#926 Functional politician: Replacing Default Collection Avatars
  .glitch-assets
  package.json
  shrinkwrap.yaml
  src/components/collection/collection-avatar.js
  src/components/collection/collection-avatar.styl
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/collection-patterns.js
  src/components/collection/collection-result-item.js
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/collections-list/index.js
  src/components/collections-list/more-collections.js
  src/components/collections-list/styles.styl
  src/components/containers/cover-container.styl
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/images/avatar.js
  src/components/search-results/index.js
  src/components/search-results/search-results.styl
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/home-v2/styles.styl
  src/presenters/pages/project.js
  src/utils/color.js
Labels: Under Review

#922 Nova chance: Server side render collection/team/user pages
  server/api.js
  server/routes.js
  shared/api-loaders.js
  src/components/team-users/team-user-info.js
  src/models/team.js
  src/presenters/pages/collection.js
  src/presenters/pages/team-or-user.js
  src/presenters/pages/team.js
  src/state/api-cache.js
  src/state/team.js
  src/state/user.js
Labels: Ready to merge

#915 Pool rodent - Private Collections
  src/components/buttons/bookmark-button.styl
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/collection-result-item.js
  src/components/collection/collection-result-item.styl
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/fields/hidden-checkbox.styl
  src/components/private-badge/index.js
  src/components/private-badge/styles.styl
  src/components/project/add-project-to-collection-pop.js
  src/components/tooltips/tooltip.styl
  src/models/collection.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/state/collection.js
  src/state/search.js
Labels: Waiting on Reviews
