Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-03, with the labels that each got.

#308 Text / Markdown
  src/components/text/markdown.js
  src/components/text/markdown.styl
  src/presenters/collection-item.js
  src/presenters/featured-collections.js
  src/presenters/includes/description-field.js
  src/presenters/includes/markdown.js
  src/presenters/overlays/new-stuff.js
  src/presenters/pages/project.js
  src/presenters/project-item.js
  src/presenters/team-item.js
  src/presenters/user-item.js
  stories/index.js
  styles/styles.styl
Labels: Ready to merge

#311 Text / Heading
  src/components/text/heading.js
  src/components/text/heading.styl
  src/presenters/pages/user.js
  stories/index.js
Labels: Ready to merge

#314 Modifications to logging
  server/logger.js
Labels: Waiting on Reviews

#317 Text / Heading - Replacement
  src/presenters/collections-list.js
  src/presenters/deleted-projects.js
  src/presenters/entity-page-featured-project.js
  src/presenters/featured-collections.js
  src/presenters/featured-embed.js
  src/presenters/more-ideas.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/error.js
  src/presenters/pages/index.js
  src/presenters/pages/project.js
  src/presenters/pages/search.js
  src/presenters/pages/team.js
  src/presenters/projects-list.js
  src/presenters/questions.js
  src/presenters/recent-projects.js
Labels: Ready to merge

#327 Text - Text
  src/components/text/heading.js
  src/components/text/text.js
  src/components/text/text.styl
  src/presenters/collection-item.js
  src/presenters/footer.js
  src/presenters/includes/name-conflict.js
  src/presenters/includes/not-found.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-analytics.js
  src/presenters/includes/team-elements.js
  src/presenters/notifications.js
  src/presenters/overlays/new-stuff.js
  src/presenters/pages/collection.js
  src/presenters/pages/error.js
  src/presenters/pages/index.js
  src/presenters/pages/team.js
  stories/index.js
Labels: Ready to merge

#319 Add a CSP and a few headers to improve security
  .shrinkwrap.yaml.swp
  package.json
  server/constants.js
  server/routes.js
  shrinkwrap.yaml
  views/index.ejs
Labels: Waiting on Reviews

#378 Ninth doom - fixed storybook for badges and segmented buttons
  src/components/badges/badge.js
  stories/index.js
  styles/pop-overs.styl
Labels: Ready to merge

#374 Instinctive diagram: miscellaneous hookifications
  src/presenters/includes/konami.js
  src/presenters/pages/collection.js
  src/presenters/pages/router.js
  src/presenters/pages/secret.js
  src/presenters/pop-overs/new-project-pop.js
  src/presenters/projects-list.js
Labels: Ready to merge

#375 Olive team: Show Collection Notes on the Homepage
  src/curated/collections.js
  src/presenters/featured-collections.js
  src/presenters/project-item.js
  src/presenters/projects-list.js
  styles/collections.styl
Labels: Ready to merge

#379 Fix for the underscore in username collections bug in production
  src/presenters/pages/collection.js
Labels: Ready to merge

#385 Nova chance: new embed support check that should be more reliable
  package.json
  shrinkwrap.yaml
  src/presenters/includes/embed.js
Labels: Waiting on Reviews

#383 Stupendous fisher 1: Fix aria-labelledby errors in avatar tooltip container
  src/components/tooltips/tooltip-container.js
Labels: Ready to merge

#381 Spurious attack: add collections to search (algolia only)
  src/presenters/pages/search.js
  src/state/search.js
  styles/collections.styl
  styles/pages/search.styl
Labels: Under Review
