Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-07, with the labels that each got.

#617 Foggy leopon: add aria labels to private project signifiers
  src/components/banners/super-user.js
  src/components/collection/collection-item-small.js
  src/components/fields/hidden-checkbox.js
  src/components/fields/hidden-checkbox.styl
  src/components/fields/project-domain-input.js
  src/components/private-badge/index.js
  src/components/private-badge/styles.styl
  src/components/project/project-item.js
  src/presenters/pages/project.js
  src/presenters/pages/project.styl
  src/presenters/pages/secret.js
  src/presenters/pages/secret.styl
  stories/inputs.js
  styles/buttons.styl
  styles/styles.styl
Labels: Waiting on Reviews

#685 Rambunctious bathroom: bug fixes for project page
  src/components/related-projects/index.js
  src/presenters/pages/project.js
Labels: Ready to merge

#677 Profuse tea: Don't show 'edit project' on featured projects you are not a member of
  src/components/buttons/button.styl
  src/components/project/featured-project.js
  src/components/project/project-embed.js
  src/presenters/pages/project.js
  stories/index.js
Labels: Ready to merge

#680 Stormy tarsier: unicode arrow component
  src/components/arrow/index.js
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/container.js
  src/components/collections-list/more-collections.js
  src/components/containers/results-list.js
  src/components/new-stuff/new-stuff-article.js
  src/components/questions/index.js
  src/components/recent-projects/index.js
  src/components/related-projects/index.js
  src/components/search-form/autocomplete.js
  src/presenters/featured-embed.js
  stories/inputs.js
Labels: Waiting on Reviews

#678 Innate tractor: Componentize progress, input styles
  src/components/fields/progress.js
  src/components/fields/progress.styl
  src/components/inputs/text-input.styl
  src/components/team-analytics/team-analytics-referrers.js
  src/state/uploader.js
  stories/index.js
  styles/inputs.styl
  styles/styles.styl
Labels: Ready to merge

#674 Gaudy report: hookify current user
  src/components/popover/container.js
  src/state/current-user.js
Labels: Waiting on Reviews

#683 Abstracted droplet: normalize project options
  src/components/collection/container.js
  src/components/collections-list/more-collections.js
  src/components/profile-list/index.js
  src/components/project/featured-project.js
  src/components/project/project-embed.js
  src/components/project/project-item.js
  src/components/project/project-options-pop.js
  src/components/search-results/index.js
  src/models/project.js
  src/models/team.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/state/collection.js
  src/state/project-options.js
  src/state/project.js
  src/state/team.js
  src/state/user.js
Labels: Ready to merge

#694 Curious teller: cleanup tooltip styles
  src/components/tooltips/tooltip-container.js
  src/components/tooltips/tooltip.styl
  styles/styles.styl
  styles/tooltips.styl
Labels: Ready to merge

#695 Pond powder: random bug fixes related to adding a project to a collection
  src/components/containers/results-list.styl
  src/components/popover/container.js
  src/components/project/project-embed.js
  src/state/collection.js
  src/state/notifications.js
Labels: Waiting on Reviews

#696 Little health: fix input css
  src/presenters/pages/project.styl
Labels: Waiting on Reviews

#697 Mewing owner: clicking 'Create Team' should ... create team
  src/components/create-team-pop/index.js
Labels: Waiting on Reviews

#670 Superb guide: Use a shared local storage cache
  src/app.js
  src/state/dev-toggles.js
  src/state/local-storage.js
  src/state/user-prefs.js
Labels: Waiting on Reviews

#692 Nova chance: Two factor auth backup codes
  src/components/account-settings-overlay/styles.styl
  src/components/account-settings-overlay/two-factor-settings.js
  src/components/sign-in/two-factor-form.js
Labels: Ready to merge

#700 Ninth berry: fix preview projects
  src/components/collection/container.js
Labels: Waiting on Reviews

#699 Prickly swim: fix default button styles
  src/components/images/emoji.js
  src/presenters/pages/index.js
  styles/globals.styl
Labels: Ready to merge

#702 Vagabond racer: include project permissions in freshly deleted projects
  src/state/user.js
Labels: Waiting on Reviews

#715 Brief shrimp: fix popover css
  sh/merge.sh
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/home-v2/styles.styl
Labels: Waiting on Reviews

#717 Tundra beat: VSCode auth design changes
  .glitch-assets
  src/components/buttons/sign-in-button.js
  src/components/images/emoji.js
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
  src/components/sign-in-pop/index.js
  src/components/sign-in/get-magic-code.js
  src/components/sign-in/password-login.js
  src/components/sign-in/use-magic-code.js
  src/presenters/pages/vscode-auth.js
  src/presenters/pages/vscode-auth.styl
Labels: Ready to merge

#720 Neighborly pull: fix resend invite on team pages
  src/components/team-users/index.js
Labels: Ready to merge

#679 Twisty citrus: caching documentation
  FAQ.md
  src/presenters/pages/index.js
Labels: Ready to merge

#718 steadfast-ticket: don't use VisibilityContainer on /create
  src/presenters/pages/create.js
Labels: Ready to merge

#705 Superb guide: move constants into a shared file
  server/constants.js
  server/routes.js
  shared/constants.js
  src/client.js
  src/components/buttons/sign-in-button.js
  src/components/containers/profile/story.js
  src/components/header/index.js
  src/components/project/embed.js
  src/models/collection.js
  src/models/project.js
  src/models/team.js
  src/models/user.js
  src/presenters/pages/login.js
  src/presenters/pages/signin.js
  src/state/api.js
  src/utils/abuse-reporting.js
  src/utils/constants.js
  stories/util.js
  storybook-config/config.js
  views/index.ejs
Labels: Ready to merge

#701 Cassey-community: Some semantic fixes + add breadcrumb for weird Sentry issue
  src/components/containers/results-list.js
  src/components/deleted-projects/index.js
  src/components/link/index.js
  src/components/popover/index.js
Labels: Ready to merge

#698 Quixotic rocket: Fix 'more collections by' display
  src/components/collections-list/more-collections.js
  src/components/create-team-pop/index.js
Labels: Ready to merge

#723 Wakeful scent: fix dropdown bug
  src/components/popover/styles.styl
  src/curated/collections.js
Labels: Waiting on Reviews

#660 Butter sunspot: Replace system prompts with happy popovers
  src/components/collection/collection-options-pop.js
  src/components/collection/delete-collection-pop.js
  src/presenters/pages/collection.js
Labels: Under Review

#704 Pond powder: fix `Take me there` links
  src/components/data-loader/index.js
  src/components/link/index.js
  src/presenters/pages/collection.js
  src/presenters/pages/router.js
  src/state/collection.js
Labels: Ready to merge

#726 Superb-guide: Remove a workaround that isn't needed any more
  src/state/api.js
Labels: Ready to merge

#711 Profuse tea: Fix a race condition in user loading
  src/components/sign-in-pop/index.js
  src/state/current-user.js
Labels: Ready to merge

#722 Fix semantic errors in HTML
  src/components/badges/badge.js
  src/components/buttons/button.js
  src/components/team-analytics/team-analytics-project-pop.js
  src/components/text/markdown.js
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#613 gentle-fireman: announce notifications with aria-live
  src/app.js
  src/components/notification/index.js
  src/components/notification/styles.styl
  src/state/uploader.js
Labels: Under Review

#728 Cassey-community: fix title on create page for embeds
  src/components/project/embed.js
  src/curated/embed.js
Labels: Ready to merge

#729 Superb guide: Fix globals use in sentry, move collection color functions into utils/color
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/collection/edit-collection-color-pop.js
  src/components/collection/note.js
  src/models/collection.js
  src/utils/color.js
  src/utils/constants.js
  src/utils/sentry.js
Labels: Ready to merge

#732 Foregoing-spell: move focus back to popover-opening-button after a popover is closed with keyboard
  src/components/popover/container.js
  src/components/popover/index.js
Labels: Ready to merge

#738 Sunset charger: add .babelrc file to storybook config
  storybook-config/.babelrc
  storybook-config/webpack.config.js
Labels: Ready to merge

#734 plastic-climb: fix Markdown component HTML validation
  src/components/text/markdown.js
Labels: Ready to merge

#740 Superb guide: Replace a bunch of anchor tags with link components
  src/components/collection/collection-item-small.js
  src/components/link/index.js
  src/components/search-form/autocomplete.js
  src/components/search/starter-kit-result.js
  src/models/collection.js
  src/presenters/pages/home-v2/collection-container.js
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/team.js
Labels: Waiting on Reviews

#703 Nova chance: Fix question reloading, hide name/description for suspended projects
  src/components/link/index.js
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/components/questions/index.js
  src/components/questions/questions.styl
Labels: Ready to merge

#731 Cassey-community: a11y small fixes
  src/components/buttons/button.js
  src/components/containers/visually-hidden.js
  src/components/more-ideas/index.js
  src/components/verified-badge/index.js
  src/presenters/pages/questions.js
  src/presenters/pages/search.js
  src/presenters/pages/secret.js
Labels: Waiting on Reviews

#733 woozy-shoemaker: 4 dev toggles :P
  src/state/dev-toggles.js
Labels: Ready to merge

#744 Understood basin: separate button visibility from onClick
  src/components/project/project-options-pop.js
Labels: Ready to merge

#725 Neighborly pull: Fetch missing permissions for search page
  src/components/search-results/index.js
  src/state/project-options.js
  src/state/search.js
Labels: Ready to merge

#741 Close tooltips with escape key
  src/components/tooltips/tooltip-container.js
Labels: Ready to merge

#746 Superb guide: Several changes to support server side rendering
  src/app.js
  src/client.js
  src/components/containers/profile/project.js
  src/components/link/index.js
  src/presenters/pages/home-v2/index.js
  src/state/api.js
  src/state/current-user.js
  src/state/globals.js
  src/state/local-storage.js
  src/state/offline-notice.js
  src/state/project.js
  src/state/team.js
  src/utils/abuse-reporting.js
  src/utils/constants.js
  src/utils/models.js
Labels: Ready to merge

#749 Superb-guide: Fix invalid attempt to spread... + some notification regressions
  src/state/notifications.js
  src/state/uploader.js
Labels: Waiting on Reviews

#751 Quixotic rocket: Fix link components using hash/relative urls
  src/components/link/index.js
  src/state/globals.js
Labels: Waiting on Reviews

#747 Nova chance: Updated a bunch of packages and removed ProgressPromise
  .babelrc
  package.json
  server/home.js
  shrinkwrap.yaml
  src/components/fields/progress.styl
  src/state/notifications.js
  src/utils/assets.js
  src/utils/progress-promise.js
  src/utils/s3-uploader.js
Labels: Ready to merge

#754 Nova-chance: Fix race condition with requests made on initial page load
  src/state/api.js
Labels: Ready to merge

#753 Superb-guide: Fix an error caused by search results that don't exist
  src/state/api.js
  src/state/project-options.js
Labels: Ready to merge

#752 Cassey-community: skip links
  .gitconfig
  .gitignore
  src/components/buttons/button.js
  src/components/header/header.styl
  src/components/header/index.js
  src/components/layout/index.js
  src/components/link/index.js
  src/components/search-results/index.js
  src/hooks/use-focus-first.js
  src/presenters/pages/collection.js
  src/presenters/pages/create.js
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/project.js
  src/presenters/pages/search.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
Labels: Ready to merge

#636 first-adapter: add ids to headings in READMEs so users can write fragment links
  package.json
  shrinkwrap.yaml
  src/components/buttons/checkbox-button.js
  src/components/deleted-projects/index.js
  src/components/images/avatar.js
  src/components/new-stuff/index.js
  src/components/new-stuff/new-stuff-prompt.js
  src/components/private-badge/index.js
  src/components/team-analytics/team-analytics-project-details.js
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
  src/components/text/markdown.js
  src/components/tooltips/tooltip-container.js
  src/components/tooltips/tooltip.styl
  src/components/user-options-pop/index.js
  src/components/verified-badge/index.js
  src/presenters/pages/project.js
  src/presenters/pages/router.js
  stories/index.js
Labels: Ready to merge

#750 Woozy shoemaker: Adding `My Stuff` to User Pages
  src/components/collection/collection-item.js
  src/components/collection/edit-collection-color-pop.js
  src/components/collections-list/index.js
  src/models/collection.js
  src/presenters/pages/user.js
  src/utils/color.js
Labels: Ready to merge

#755 fern-street: implement pagination and filtering for collections
  src/components/collection/collection-item.js
  src/components/collections-list/index.js
  src/components/containers/projects-list.js
  src/components/containers/projects-list.styl
  src/components/filter-controller/index.js
  src/components/filter-controller/styles.styl
  src/components/pagination-controller/index.js
  src/components/pagination-controller/styles.styl
  src/presenters/pages/team.js
  src/presenters/pages/user.js
Labels: Ready to merge

#756 fern-street: fix small typo so paginated items load smoothly
  src/components/collection/collection-item.js
  src/components/collections-list/index.js
Labels: Ready to merge

#730 hazel-judge: Load Wistia scripts early, so landing page videos load faster
  server/routes.js
  src/components/wistia-video/index.js
Labels: Under Review

#669 Defiant-Okra: Update package.json and fix conflicts
  package.json
  shrinkwrap.yaml
  src/state/search.js
  webpack.config.js
Labels: WIP

#758 Cassey-community: skip section buttons in project lists
  package-lock.json
  src/components/containers/projects-list.js
  src/components/containers/skip-section-buttons.js
  src/components/containers/skip-section-buttons.styl
  src/components/layout/index.js
  src/presenters/pages/user.js
Labels: Ready to merge

#762 solstice-poinsettia: Make tooltips hoverable and text within tooltips selectable
  src/components/filter-controller/index.js
  src/components/profile-list/index.js
  src/components/team-users/add-team-user.js
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
  src/components/tooltips/tooltip-container.js
  src/components/tooltips/tooltip.styl
Labels: Ready to merge

#721 Indecisive expert - Improved Focus Styling for new landing pages
  .glitch-assets
  src/components/header/header.styl
  src/presenters/pages/create.styl
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/home-v2/banner.styl
Labels: Ready to merge

#727 tundra-beat: Create useEmail hook
  src/components/sign-in-pop/index.js
  src/components/sign-in/get-magic-code.js
  src/components/sign-in/password-login.js
  src/hooks/use-email.js
Labels: Ready to merge

#761 Prioritize the hostname for determining environment-specific constants.
  src/utils/constants.js
Labels: Ready to merge

#735 tourmaline-jade: Add <Video> component
  src/components/video/index.js
  src/presenters/pages/create.js
  stories/index.js
  storybook-config/.babelrc
  storybook-config/webpack.config.js
Labels: Ready to merge

#716 Chiseled sawfish: remove old homepage
  src/curated/collections.js
  src/curated/embed.js
  src/curated/featured-embed.js
  src/curated/featured.js
  src/presenters/featured-collections.js
  src/presenters/featured-embed.js
  src/presenters/featured.js
  src/presenters/overlays/overlay-video.js
  src/presenters/pages/index.js
  src/presenters/pages/router.js
  styles/includes/featured.styl
  styles/includes/projects-collections-teams-users-container.styl
  styles/includes/what-is-glitch.styl
  styles/includes/zine-items.styl
  styles/overlays.styl
  styles/styles.styl
  styles/what-is-glitch-black-container.styl
  styles/what-is-glitch-pastels.styl
Labels: Ready to merge

#764 Cassey-community-3: skip buttons wrapping collection section, too
  src/components/collections-list/index.js
Labels: Ready to merge

#763 Fallacious slice: First pass at server side rendering
  STYLE.md
  package.json
  server/render.js
  server/routes.js
  server/server.js
  shrinkwrap.yaml
  src/client.js
  src/components/data-loader/index.js
  src/components/header/logo.js
  src/components/images/mask-image.js
  src/components/link/index.js
  src/components/questions/index.js
  src/components/search-form/index.js
  src/presenters/pages/error.js
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/router.js
  src/server.js
  src/utils/constants.js
  src/utils/sentry.js
  views/index.ejs
Labels: Under Review

#769 Nova chance: Fix issues that were causing ssr not to apply
  server/render.js
  server/routes.js
  src/components/video/index.js
  src/hooks/use-unique-id.js
  src/hooks/use-window-size.js
  src/presenters/pages/create.js
  src/presenters/pages/create.styl
  src/server.js
Labels: Ready to merge

#770 bodega-boys: make sure search queries are URL-encoded
  src/components/search-form/index.js
  src/presenters/pages/search.js
Labels: Ready to merge

#757 Efficacious deposit: start work on getting "my stuff" button inside popovers
  .glitch-assets
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/collection-result-item.js
  src/components/collection/container.js
  src/components/collection/create-collection-pop.js
  src/components/collections-list/index.js
  src/components/images/avatar.js
  src/components/project/add-project-to-collection-pop.js
  src/models/collection.js
  src/presenters/pages/user.js
  src/state/collection.js
Labels: Ready to merge

#776 Adhesive hero: fix broken homepage publishing
  server/home.js
  src/presenters/pages/home-v2/index.js
  src/state/globals.js
Labels: Under Review

#774 ninth-winter: add documentation about running ~community locally
  FAQ.md
Labels: Waiting on Reviews

#775 Grizzled lamprey: Add MyStuff button to project pages
  .glitch-assets
  src/components/buttons/bookmark-button.js
  src/components/buttons/bookmark-button.styl
  src/components/collection/collection-item.js
  src/components/images/avatar.js
  src/presenters/pages/project.js
  src/presenters/pages/project.styl
  src/state/collection.js
Labels: Ready to merge

#779 Superb-guide: Load collection projects in order
  src/state/collection.js
Labels: Ready to merge

#777 Nova chance: Fix some small inconsistencies with SSR
  src/client.js
  src/components/fields/hidden-checkbox.js
  src/components/user-options-pop/index.js
  src/presenters/pages/project.js
Labels: Ready to merge

#778 Turquoise beetle: Update Collection pages to properly render "My Stuff"
  src/components/collection/container.js
  src/components/images/avatar.js
  src/presenters/pages/collection.js
Labels: Ready to merge

#780 Fuschia canoe: Filter out "My Stuff" from "More by" and "Included in" sections
  src/components/collections-list/more-collections.js
  src/presenters/pages/project.js
Labels: Ready to merge
