Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-08, with the labels that each got.

#785 Nova-chance: Restore the remove project from team button
  src/state/team.js
Labels: Ready to merge

#784 Quixotic rocket: Use updatedAt for image cache busting, differentiate getLink names
  src/components/collection/delete-collection-pop.js
  src/components/containers/cover-container.js
  src/components/containers/profile/project.js
  src/components/containers/profile/team.js
  src/components/containers/profile/user.js
  src/components/create-team-pop/index.js
  src/components/deleted-projects/index.js
  src/components/images/avatar.js
  src/components/link/index.js
  src/components/project/project-item-small.js
  src/components/project/project-item.js
  src/components/project/project-result-item.js
  src/components/recent-projects/index.js
  src/components/search-form/index.js
  src/components/search-result-cover-bar/index.js
  src/components/team/team-item.js
  src/components/user-options-pop/index.js
  src/components/user/user-item.js
  src/models/collection.js
  src/models/project.js
  src/models/team.js
  src/models/user.js
  src/presenters/pages/collection.js
  src/presenters/pages/create.js
  src/presenters/pages/home-v2/collection-container.js
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/join-team.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/utils/abuse-reporting.js
  src/utils/models.js
Labels: Ready to merge

#783 Consistent Community 404 Illustration
  src/components/errors/not-found.js
  src/components/errors/not-found.styl
  src/components/filter-controller/index.js
  src/components/filter-controller/styles.styl
  src/presenters/pages/error.js
  src/presenters/pages/error.styl
Labels: Waiting on Reviews

#782 Coherent nylon: My Stuff bookmark icon focus styling
  .glitch-assets
  src/components/buttons/bookmark-button.js
  src/components/buttons/bookmark-button.styl
Labels: Under Review

#789 Nova chance: Prefer to build collection urls over fullUrl, fix collection page renaming
  src/models/collection.js
  src/presenters/pages/collection.js
Labels: Waiting on Reviews

#795 Hungry pipe: fix super user button styling
  src/components/user-options-pop/index.js
  src/curated/home.json
Labels: Ready to merge

#792 Olive staircase: don't name collections My Stuff
  src/components/collection/create-collection-pop.js
Labels: Ready to merge

#797 Nova-chance: Fix the site in the vivaldi browser
  src/utils/constants.js
Labels: Ready to merge

#794 Quixotic rocket: Fix add to collection title styling, fix a proptypes warning
  src/components/images/avatar.js
  src/components/images/avatar.styl
  src/components/popover/styles.styl
  src/components/project/add-project-to-collection-pop.js
  src/components/project/popover.styl
  src/components/user-options-pop/index.js
  src/components/user-options-pop/styles.styl
  src/presenters/pages/team.js
Labels: Under Review

#796 Rustic bat 1: add starterKit to filters
  src/components/search-results/search-results.styl
  src/state/search.js
Labels: Ready to merge

#790 Eight truck: My stuff button on project items, notifications
  .glitch-assets
  src/components/buttons/bookmark-button.js
  src/components/buttons/bookmark-button.styl
  src/components/images/image.js
  src/components/notification/styles.styl
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/components/search-results/index.js
  src/state/collection.js
  src/state/project-options.js
Labels: Ready to merge

#798 Pickle suggestion: small style fixes
  src/components/collection/container.js
  src/components/tooltips/tooltip.styl
  src/presenters/pages/project.js
Labels: Ready to merge

#801 best-hammer: Add support for native lazy-loading to image and embed components
  src/components/images/image.js
  src/components/project/embed.js
  src/components/project/project-embed.js
Labels: Ready to merge

#804 periodic-weeder: Fix overflow of note on featured project
  src/components/project/featured-project.styl
Labels: Ready to merge

#799 Nova chance: A few fixes for collection and team pages
  src/components/collection/add-collection-project-pop.js
  src/components/collections-list/index.js
  src/components/containers/results-list.js
  src/components/pagination-controller/index.js
  src/components/popover/search.js
  src/state/team.js
Labels: Ready to merge

#805 fix borked new stuff tooltip
  src/components/tooltips/tooltip.styl
Labels: Ready to merge

#793 Superb guide: Use the server rendered page instead of the fallback in some cases
  src/client.js
  src/components/header/index.js
  views/index.ejs
Labels: Ready to merge

#809 Nova chance: Update shrinkwrap without updating every package
  shrinkwrap.yaml
Labels: Ready to merge

#802 jolly-hardboard: make autoplay videos work on iOS Safari
  src/components/video/index.js
Labels: Ready to merge

#806 Dramatic haddock: proxy community home editor
  server/proxy.js
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#800 flat-staircase: code-splitting, dynamic imports, compressed images, and other perf improvements
  .babelrc
  .glitch-assets
  package-lock.json
  package.json
  shrinkwrap.yaml
  src/components/account-settings-overlay/two-factor-settings.js
  src/components/collection/create-collection-pop.js
  src/components/images/emoji.js
  src/components/images/emoji.styl
  src/models/user.js
  src/presenters/pages/home-v2/collection-container.js
  src/presenters/pages/home-v2/index.js
  webpack.config.js
Labels: Ready to merge

#810 Garrulous season: styling links in collection descriptions
  src/components/collection/collection-item.styl
  src/components/text/markdown.styl
Labels: Ready to merge

#791 Sponge credit: add analytics events for my stuff button
  src/components/project/project-item.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/search.js
  src/presenters/pages/team.js
Labels: Ready to merge

#812 Kaput aftermath: fix main element
  views/index.ejs
Labels: Waiting on Reviews

#813 Celestial can: fix bug i just introduced
  src/components/search-results/index.js
Labels: Ready to merge

#817 add back descriptions to my stuff in add to collection popover
  src/components/collection/collection-result-item.js
Labels: Ready to merge

#814 Buttercup nickel: Update collections to show latest projects + fix aria-labels on my stuff button
  src/components/buttons/bookmark-button.js
  src/components/fields/hidden-checkbox.js
  src/components/project/project-item.js
  src/presenters/pages/project.js
  src/state/collection.js
Labels: Ready to merge

#808 Whispering handball: Add My Stuff Button to featured projects, edited Notes placement
  src/components/buttons/bookmark-button.styl
  src/components/collection/note.styl
  src/components/containers/projects-list.styl
  src/components/project/featured-project.js
  src/components/project/featured-project.styl
  src/components/project/project-item.styl
  src/presenters/pages/project.styl
Labels: Ready to merge

#818 Mulberry morocco: fix take me there link on mystuff creation
  src/state/collection.js
Labels: Ready to merge

#787 Fallacious slice: Server rendering for project pages with new api cache
  server/api.js
  server/render.js
  server/routes.js
  src/app.js
  src/client.js
  src/presenters/pages/project.js
  src/server.js
  src/state/api-cache.js
  src/state/project.js
  views/index.ejs
Labels: Ready to merge

#826 Fallacious-slice: Disable ssr for project pages and remove the extra data loading
  server/api.js
  server/routes.js
Labels: Waiting on Reviews

#823 Coordinated-tracker: tooltips on user/team avatars should appear on focus
  src/components/profile-list/index.js
Labels: Ready to merge

#822 Polyester wallet: bookmark button should update when we add a project to My stuff from popover
  src/components/project/project-item.js
  src/presenters/pages/project.js
  src/state/project.js
Labels: Ready to merge

#830 Slash second: more my stuff bugs
  src/components/buttons/bookmark-button.styl
  src/components/project/featured-project.js
Labels: Ready to merge

#815 Wealthy daughter: best a11y practices for team analytics time filter
  src/components/team-analytics/styles.styl
  src/components/team-analytics/team-analytics-time-pop.js
Labels: Waiting on Reviews

#829 Updated Collection Reordering Instruction UI
  .glitch-assets
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/containers/grid.js
  src/components/containers/grid.styl
  src/components/containers/projects-list.styl
  src/components/images/emoji.js
Labels: Ready to merge

#832 jazzy-packet: fix source maps in development mode
  src/components/profile-list/index.js
  webpack.config.js
Labels: Ready to merge

#828 Quixotic rocket: Fix leaving team projects, fix joining teams via email whitelist
  src/components/project/project-options-pop.js
  src/state/team.js
Labels: Ready to merge

#827 Pebble-fragrance: add a table view of the analytics graphs
  src/components/team-analytics/styles.styl
  src/components/team-analytics/team-analytics-activity.js
Labels: Under Review

#824 Curved panther: 🐆 when hovering on a note the bookmark button should appear
  src/components/containers/projects-list.js
  src/components/containers/projects-list.styl
  src/components/project/project-item.js
  src/components/project/project-item.styl
Labels: Ready to merge

#825 Superb guide: Memoize server rendering, standardize caching
  server/api.js
  server/cache.js
  server/render.js
  server/routes.js
  src/server.js
  views/index.ejs
Labels: Ready to merge

#839 Auto focus the pause button when wistia component appears on homepage
  src/components/wistia-video/index.js
  src/presenters/pages/home-v2/banner.js
Labels: Ready to merge

#840 Suspended-share: Sharing a suspended project shouldn't reveal the project's avatar
  server/routes.js
Labels: Ready to merge

#838 View all X projects link should be labeled equivalently to visual label
  src/components/collection/collection-item.js
  src/components/link/index.js
Labels: Ready to merge

#837 Pebble-fragrance: only show 'skip collections section' buttons when there are collections to skip
  src/components/collections-list/index.js
Labels: Ready to merge

#847 Quixotic-rocket: Fix the analytics identify call
  src/state/current-user.js
Labels: Waiting on Reviews

#863 Cooked devourer: fixes from broken deploy attempt
  server/home.js
  src/curated/pupdates.json
Labels: Waiting on Reviews

#865 Nasal harmony: fix add project to collection by url
  src/components/collection/add-collection-project-pop.js
Labels: Ready to merge

#867 Superb guide: Faster ssr compilation, better server timeouts
  server/api.js
  server/cache.js
  server/proxy.js
  server/render.js
  src/components/popover/container.js
Labels: Ready to merge

#831 Fallacious slice: Batch together api requests being made on the server
  server/api.js
Labels: Under Review, Waiting on Reviews

#870 Mulberry fuchsia: handle long project names on project pages
  src/presenters/pages/project.styl
Labels: Ready to merge
