Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-05, with the labels that each got.

#474 Coordinated mascara: componentizing note
  src/components/collection/note.js
  src/components/collection/note.styl
  src/components/containers/projects-list.js
  src/components/inputs/markdown-input.js
  src/components/inputs/markdown-input.styl
  src/components/project/featured-project.js
  src/components/project/featured-project.styl
  stories/data.js
  stories/index.js
  styles/includes/projects-collections-teams-users-container.styl
  styles/note.styl
  styles/styles.styl
Labels: Ready to merge

#486 Bronze gibbon: Fix dropdown permissions on search page, and super user bug fix
  src/presenters/overlays/super-user-banner.js
  src/presenters/pop-overs/project-options-pop.js
Labels: Waiting on Reviews

#491 Superb guide: Throw an error instead of going into an api request loop
  package.json
  shared/api.js
  shrinkwrap.yaml
Labels: Waiting on Reviews

#447 Strong duchess: enable algolia search for everyone
  src/presenters/includes/dev-toggles.js
Labels: Waiting on Reviews

#489 Outstanding pamphlet: finish componentizing ProjectsList
  src/components/containers/projects-list.js
  src/components/containers/projects-list.styl
  src/presenters/featured-collections.js
  src/presenters/includes/related-projects.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/team.js
  src/presenters/pages/team.styl
  src/presenters/pages/user.js
  src/presenters/pages/user.styl
  src/presenters/recent-projects.js
  styles/collections.styl
  styles/includes/projects-collections-teams-users-container.styl
  styles/pages/category.styl
  styles/pages/collection.styl
  styles/pages/project.styl
  styles/pages/user-and-team-page.styl
  styles/profile.styl
  styles/projects.styl
Labels: Waiting on Reviews

#494 Miniature ferry: lots of style fixes
  src/components/header/header.styl
  src/components/header/index.js
  src/presenters/pop-overs/featured-project-options-pop.js
  src/presenters/pop-overs/new-project-pop.js
  styles/pop-overs.styl
  styles/results-list.styl
Labels: Ready to merge

#485 Important alfalfa: avoid unnecessary 404s in search result images
  src/components/search-form/autocomplete.js
  src/components/search-result-cover-bar/index.js
  src/models/user.js
  src/state/search.js
Labels: Waiting on Reviews

#502 Furry record: only projects are punycoded, not usernames
  server/routes.js
  src/presenters/pages/router.js
Labels: Waiting on Reviews

#504 Nova chance: Big refactor of the add project to collection pop
  src/presenters/pop-overs/add-project-to-collection-pop.js
Labels: Waiting on Reviews

#499 Superb guide: Componentize new stuff stuff
  src/components/buttons/button.styl
  src/components/deleted-projects/deleted-projects.styl
  src/components/new-stuff/new-stuff-article.js
  src/components/new-stuff/new-stuff-article.styl
  src/components/new-stuff/new-stuff-prompt.js
  src/components/new-stuff/new-stuff-prompt.styl
  src/components/new-stuff/new-stuff-pup.js
  src/components/new-stuff/story.js
  src/components/tooltips/tooltip.styl
  src/presenters/overlays/new-stuff.js
  storybook-config/config.js
  styles/new-stuff.styl
Labels: Ready to merge

#490 Helix tyrannosaurus: Webpack space issues
  webpack.config.js
Labels: Ready to merge

#503 Bunch of small design regression fixes
  src/components/containers/cover-container.styl
  src/components/containers/projects-list.styl
  src/components/inputs/text-area.styl
  src/components/profile-container/styles.styl
  src/components/profile-list/profile-list.styl
  src/presenters/pop-overs/report-abuse-pop.js
  styles/icons.styl
  styles/pages/collection.styl
  styles/profile.styl
Labels: Ready to merge

#510 Adhesive mascara: refactor team users + popovers
  src/models/team.js
  src/presenters/includes/add-team-project.js
  src/presenters/includes/delete-team.js
  src/presenters/includes/team-users.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/delete-team-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
Labels: Waiting on Reviews

#507 Lemon molecule: Add User / Team Toggle to Add project to collection pop
  src/components/buttons/segmented-buttons.styl
  src/components/inputs/text-input.styl
  src/presenters/pop-overs/add-project-to-collection-pop.js
Labels: Ready to merge

#512 Faceted vase: use AnimationContainer for project & collection popup actions
  src/components/animation-container/index.js
  src/components/collection/collection-item.js
  src/components/deleted-projects/index.js
  src/components/project/project-item.js
  src/presenters/pop-overs/collection-options-pop.js
  src/presenters/pop-overs/project-options-pop.js
Labels: Waiting on Reviews

#509 wandering-save: Show which collections a project is already in
  src/components/badges/badge.styl
  src/presenters/pop-overs/add-project-to-collection-pop.js
  styles/pop-overs.styl
Labels: Under Review

#506 Boggy ice: refactor whitelisted-domain & add-team-user-popup
  src/components/buttons/button.styl
  src/components/whitelisted-domain/index.js
  src/components/whitelisted-domain/styles.styl
  src/presenters/includes/team-elements.js
  src/presenters/includes/team-users.js
  src/presenters/includes/user-result-item.js
  src/presenters/pages/team.styl
  src/presenters/pop-overs/add-team-user-pop.js
  styles/pop-overs.styl
Labels: Ready to merge

#516 Subsequent atmosphere: encode `+` in API calls
  server/api.js
  server/routes.js
  src/presenters/featured-collections.js
  src/presenters/pages/collection.js
  src/presenters/pages/team-or-user.js
Labels: Waiting on Reviews

#515 pentagonal-pound: fix 404s on @user/team pages
  src/presenters/pages/team-or-user.js
Labels: Waiting on Reviews

#513 Pricey countess: batch user fetching in project loader
  src/presenters/projects-loader.js
Labels: Ready to merge

#518 deep-liver: collection-item AnimationContainer fix for un-authed users
  src/components/collection/collection-item.js
Labels: Waiting on Reviews

#450 luminous-buggy: add renderAsPlaintext option to Markdown option
  src/components/text/markdown.js
  src/presenters/includes/collection-result-item.js
  src/presenters/includes/project-result-item.js
Labels: Ready to merge

#505 Mirror spell: refactor team name & url inputs
  src/components/fields/team-fields.js
  src/components/fields/team-fields.styl
  src/components/fields/team-name-input.js
  src/components/fields/team-url-input.js
  src/components/team/team-item.js
  src/components/verified-badge/index.js
  src/components/verified-badge/styles.styl
  src/presenters/includes/team-elements.js
  src/presenters/pages/team.js
  stories/inputs.js
  styles/icons.styl
Labels: Waiting on Reviews

#488 High cat: Pop-over Focus
  src/.eslintrc.js
  src/presenters/includes/add-project-to-collection.js
  src/presenters/includes/delete-team.js
  src/presenters/includes/edit-collection-color.js
  src/presenters/includes/team-users.js
  src/presenters/pages/project.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/collection-options-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/delete-team-pop.js
  src/presenters/pop-overs/edit-collection-color-pop.js
  src/presenters/pop-overs/featured-project-options-pop.js
  src/presenters/pop-overs/new-project-pop.js
  src/presenters/pop-overs/popover-container.js
  src/presenters/pop-overs/popover-with-button.js
  src/presenters/pop-overs/project-options-pop.js
  src/presenters/pop-overs/sign-in-pop.js
  src/presenters/pop-overs/team-analytics-time-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
  src/presenters/pop-overs/user-options-pop.js
Labels: Ready to merge

#501 Boiling sunflower: Hide suspended project details
  .glitch-assets
  src/components/buttons/tracked-button-group.js
  src/components/buttons/tracked-button.js
  src/components/containers/cover-container.js
  src/components/containers/profile/index.js
  src/components/containers/profile/project.js
  src/components/containers/profile/story.js
  src/components/containers/profile/styles.styl
  src/components/containers/profile/team.js
  src/components/containers/profile/user.js
  src/components/profile-container/index.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
Labels: Ready to merge

#524 Coconut restaurant (yet again): fixing project popovers
  src/presenters/pages/collection.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/project-options-pop.js
  src/presenters/user-editor.js
Labels: Under Review

#514 Darkened tilapia: check for presence of result in filter
  src/presenters/pop-overs/add-collection-project-pop.js
Labels: Ready to merge

#520 Stupendous cannon: Super users can view deleted projects
  src/components/deleted-projects/index.js
  src/presenters/pages/user.js
Labels: Ready to merge

#511 Jagged flea: thread api through DataLoader
  src/components/collections-list/more-collections.js
  src/components/data-loader/index.js
  src/presenters/featured-collections.js
  src/presenters/includes/related-projects.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/router.js
  src/presenters/pages/team-or-user.js
  src/presenters/pages/team.js
  src/state/api.js
Labels: Under Review

#531 Near grandparent: move segment analytics into state
  shared/aliases.js
  src/app.js
  src/components/buttons/tracked-button.js
  src/components/collections-list/index.js
  src/components/deleted-projects/index.js
  src/components/header/index.js
  src/components/link/index.js
  src/components/link/tracked-external-link.js
  src/components/project/project-embed.js
  src/presenters/includes/team-users.js
  src/presenters/overlays/new-stuff.js
  src/presenters/overlays/overlay-video.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/index.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/add-collection-project-pop.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/new-project-pop.js
  src/presenters/pop-overs/project-options-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
  src/presenters/pop-overs/user-options-pop.js
  src/state/segment-analytics.js
Labels: Waiting on Reviews

#519 Jet socks: modularize new project pop
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/header/index.js
  src/components/header/new-project-pop.js
  src/components/header/new-project-pop.styl
  src/components/popover/container.js
  src/components/popover/dialog.js
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/presenters/pop-overs/new-project-pop.js
Labels: Waiting on Reviews

#493 Quixotic rocket: Some overlay components
  src/components/overlays/index.js
  src/components/overlays/overlays.styl
  src/components/overlays/story.js
  src/presenters/overlays/new-stuff.js
  src/presenters/overlays/overlay-video.js
  src/presenters/pages/index.js
  storybook-config/config.js
  styles/new-stuff.styl
  styles/overlays.styl
Labels: Under Review

#537 Sideways sound: don't fetch team invitees if there aren't any
  src/presenters/includes/team-users.js
Labels: Waiting on Reviews

#527 Noisy scale: sign-in pop
  src/components/header/index.js
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/components/sign-in-pop/index.js
  src/components/sign-in-pop/styles.styl
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/sign-in-pop.js
  src/presenters/recent-projects.js
  styles/profile.styl
Labels: Under Review

#528 Neighborly child: consolidate popovers
  src/components/project/project-embed.js
  src/presenters/includes/add-collection-project.js
  src/presenters/includes/add-project-to-collection.js
  src/presenters/includes/add-team-project.js
  src/presenters/includes/delete-team.js
  src/presenters/includes/edit-collection-color.js
  src/presenters/includes/team-users.js
  src/presenters/pages/collection.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/add-collection-project-pop.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/add-team-project-pop.js
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/delete-team-pop.js
  src/presenters/pop-overs/edit-collection-color-pop.js
  src/presenters/pop-overs/project-options-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
Labels: Waiting on Reviews

#529 Slime marmot: componentize Recent Projects
  src/components/containers/profile/story.js
  src/components/recent-projects/index.js
  src/components/recent-projects/styles.styl
  src/presenters/pages/index.js
  src/presenters/recent-projects.js
  stories/index.js
  stories/util.js
  styles/profile.styl
Labels: Waiting on Reviews

#530 Mercurial parallelogram: move wrapping-link to link component
  src/components/link/index.js
  src/components/link/wrapping-link.js
  src/components/team/team-item.js
Labels: Waiting on Reviews

#541 Workable salad: fix timestamp in super user banner
  src/components/banners/super-user.js
Labels: Ready to merge

#532 Quilted day: componentize RelatedProjects
  src/components/containers/projects-list.js
  src/components/data-loader/index.js
  src/components/project/project-item.js
  src/components/related-projects/index.js
  src/components/related-projects/styles.styl
  src/presenters/includes/related-projects.js
  src/presenters/pages/project.js
  styles/pages/project.styl
Labels: Waiting on Reviews

#543 Fortunate archeology: componentize Report Abuse popover
  src/components/inputs/text-area.js
  src/components/popover/dialog.js
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/components/project/project-embed.js
  src/components/report-abuse-pop/index.js
  src/components/report-abuse-pop/styles.styl
  src/components/sign-in-pop/index.js
  src/presenters/pages/collection.js
  src/presenters/pages/index.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/report-abuse-pop.js
Labels: Waiting on Reviews

#550 Profuse tea: Fix text fields trimming the value while you're typing
  src/components/fields/optimistic-markdown-input.js
  src/components/fields/optimistic-text-input.js
  src/components/fields/optimistic-wrapping-text-input.js
  src/components/fields/use-optimistic-text.js
  src/components/fields/use-optimistic-value.js
Labels: Waiting on Reviews

#540 Superb guide: Fix project renaming, remove eager success messages
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/project-editor.js
Labels: Under Review

#553 Zest cucumber: componentize CollectionOptionsPop
  src/components/collection/collection-item.js
  src/components/collection/collection-options-pop.js
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/presenters/pop-overs/collection-options-pop.js
Labels: Waiting on Reviews

#549 Silken bandicoot
  src/components/project/project-item.js
  src/components/search-results/index.js
  src/components/team/team-item.js
  src/presenters/pop-overs/project-options-pop.js
Labels: Waiting on Reviews

#526 Humdrum triangle: The Cypress PR
  .gitignore
  TESTING.md
  cypress.json
  cypress/fixtures/userByLoginProjects.json
  cypress/integration/header_actions.js
  cypress/integration/project_page.js
  cypress/integration/user_profile.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  sh/cypress.sh
  shrinkwrap.yaml
Labels: Ready to merge

#558 Twisty citrus: emoji swap suggestion
  .glitch-assets
  src/components/footer/index.js
  src/components/images/emoji.js
Labels: Waiting on Reviews

#552 Spectrum splash: rebuild AddCollectionProjectPop
  src/components/buttons/button.js
  src/components/collection/add-collection-project-pop.js
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/popover/styles.styl
  src/components/profile-list/index.js
  src/components/profile-list/profile-list.styl
  src/components/project/project-result-item.js
  src/components/project/project-result-item.styl
  src/components/visibility-container/index.js
  src/presenters/pages/collection.js
  src/presenters/pop-overs/add-collection-project-pop.js
  src/state/search.js
Labels: Waiting on Reviews

#560 Case 3328636 featured project button & team user search need alt text
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/featured-project-options-pop.js
Labels: Ready to merge

#559 onyx-pocket: Improve metadata + social cards for team and user pages
  .glitch-assets
  server/routes.js
Labels: Ready to merge

#557 Glow cheese: componentize FeaturedProjectOptionsPop
  src/components/buttons/transparent-button.js
  src/components/images/emoji.js
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/components/project/featured-project-options-pop.js
  src/components/project/featured-project.js
  src/components/project/featured-project.styl
  src/presenters/pop-overs/featured-project-options-pop.js
Labels: Ready to merge

#555 Separated antelope: componentize DeleteTeamPop
  src/components/popover/index.js
  src/components/popover/styles.styl
  src/components/team/delete-team-pop.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/delete-team-pop.js
Labels: Ready to merge

#551 Quixotic-rocket: Filter passwords from sentry logs
  shared/sentryHelpers.js
Labels: Ready to merge

#545 Glossy wednesday: fix spellcheck issue on safari on email input
  src/components/inputs/text-input.js
Labels: Ready to merge

#567 Curse pantry: move arrow navigation to ResultsList
  src/components/collection/add-collection-project-pop.js
  src/components/containers/results-list.js
  src/components/project/project-result-item.js
Labels: Ready to merge

#570 colossal-child: Add Hooks alias
  shared/aliases.js
  src/components/fields/use-optimistic-value.js
  src/components/inputs/text-area.js
  src/components/inputs/text-input.js
  src/components/tooltips/tooltip-container.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
Labels: Waiting on Reviews

#566 Hyper flyingfish: add caching to API requests
  src/state/api.js
Labels: Ready to merge

#569 momentous-chance: autofocus email and sign-in code input in login
  src/components/sign-in-pop/index.js
Labels: Waiting on Reviews

#568 enchanted-contraption: add collections propTypes and defaultProps to CreateCollectionPop
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/create-collection-pop.js
Labels: Ready to merge

#563 quilled-tilapia: improve project page description metadata
  server/constants.js
  server/routes.js
  shared/regex.js
Labels: Ready to merge

#575 thundering-verse: only show email login validation error if input is blurred
  src/components/inputs/text-input.js
  src/components/sign-in-pop/index.js
Labels: Ready to merge

#572 Snow screwdriver: Show a meaningful error message when users try to use google translate
  src/components/link/wrapping-link.js
  src/presenters/pages/error.js
  src/presenters/pages/router.js
  views/index.ejs
Labels: Waiting on Reviews

#565 Lumpy wedge: improve image upload error handling
  src/components/animation-container/index.js
  src/presenters/includes/uploader.js
Labels: Ready to merge
