Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-06, with the labels that each got.

#578 Band rake: replace descriptive ids with data attributes on svg
  src/components/collection/defaultAvatar.js
Labels: Ready to merge

#574 Amber ophthalmologist: api PropTypes.func -> any
  src/presenters/includes/team-analytics.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/add-team-project-pop.js
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
Labels: Waiting on Reviews

#564 Frosted hammer: remove legacy search
  src/components/search-form/index.js
  src/components/search-form/story.js
  src/presenters/pages/search.js
  src/state/dev-toggles.js
  src/state/search.js
Labels: Ready to merge

#573 Quixotic legend 1: componentize team users
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/popover/base.js
  src/components/popover/container.js
  src/components/popover/index.js
  src/components/popover/search.js
  src/components/team-users/add-team-user.js
  src/components/team-users/index.js
  src/components/team-users/styles.styl
  src/presenters/includes/team-users.js
  src/presenters/pages/team.js
  src/presenters/pages/team.styl
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
Labels: Ready to merge

#571 West jumbo: Add Team Project popover
  src/components/team/add-team-project-pop.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/add-team-project-pop.js
Labels: Ready to merge

#546 Tundra beat: Some more Cypress stuff
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/userByLoginProjects.json
  cypress/integration/header_actions.js
  cypress/integration/header_actions/signIn.js
  cypress/integration/project_page.js
  cypress/integration/user_profile.js
  cypress/integration/user_profile/projectActions.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/data.js
  cypress/support/util.js
  package-lock.json
  package.json
  sh/percy.sh
  shrinkwrap.yaml
  src/components/collections-list/index.js
  src/components/containers/projects-list.js
  src/components/project/featured-project.js
  src/presenters/pages/user.js
Labels: Ready to merge

#583 Different character: sentry error
  src/components/popover/dialog.js
  src/components/profile-list/index.js
  src/curated/collections.js
Labels: Ready to merge

#582 Oceanic ornament 1: preventing tabs from outside of the new stuff dialog
  src/components/buttons/checkbox-button.js
  src/components/overlays/index.js
  src/presenters/overlays/new-stuff.js
  src/presenters/pop-overs/popover-container.js
Labels: Ready to merge

#591 aback-thread: refactor checkForCreateTeamHash
  src/presenters/pop-overs/user-options-pop.js
Labels: Ready to merge

#556 Muddy moose: componentize EditCollectionColorPop
  src/components/collection/edit-collection-color-pop.js
  src/components/collection/edit-collection-color-pop.styl
  src/components/inputs/color.js
  src/components/inputs/color.styl
  src/presenters/pages/collection.js
  src/presenters/pop-overs/edit-collection-color-pop.js
Labels: Ready to merge

#592 sprinkle-rook: add `hasEmoji` prop to add project to team button
  src/components/team/add-team-project-pop.js
  src/components/team/delete-team-pop.js
  src/presenters/pop-overs/project-options-pop.js
Labels: Ready to merge

#593 Full larch: Do not alert sentry of UC Browser bugs
  src/utils/sentry.js
Labels: Ready to merge

#586 Hexagonal gecko: color contrast warnings
  package.json
  shrinkwrap.yaml
  src/components/collection/edit-collection-color-pop.js
  src/components/collection/note.styl
  src/models/collection.js
Labels: Ready to merge

#588 wind-blade: autofocus all inputs that are the first element inside of a popover
  src/components/collection/edit-collection-color-pop.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
Labels: Ready to merge

#596 Cactus barracuda: consolidate results lists / popover search components
  src/components/buttons/transparent-button.js
  src/components/collection/add-collection-project-pop.js
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/inputs/text-input.js
  src/components/popover/search.js
  src/components/project/project-result-item.js
  src/components/project/project-result-item.styl
  src/components/team-users/add-team-user.js
  src/components/team/add-team-project-pop.js
Labels: Waiting on Reviews

#600 cat-aura: add loader to email login flow
  src/components/sign-in-pop/index.js
Labels: Ready to merge

#597 Peach countess: fix collapsing markdown inputs
  src/components/inputs/markdown-input.js
Labels: Ready to merge

#590 Halved belief: don't see undelete button if you can't undelete
  src/components/buttons/button.js
  src/components/deleted-projects/index.js
Labels: Ready to merge

#603 Remove code that renames a project on undelete
  src/presenters/user-editor.js
Labels: Ready to merge

#594 Jumbled clipper: Accessibility Contrast Audit
  .glitch-assets
  src/components/buttons/button.styl
  src/components/constants.styl
  styles/buttons.styl
  styles/c3.styl
  styles/globals.styl
  styles/includes/team-analytics.styl
Labels: Ready to merge

#562 Piquant mountain: Project Options Pop etc.
  src/components/collection/collection-result-item.js
  src/components/collection/collection-result-item.styl
  src/components/collection/create-collection-pop.js
  src/components/collection/create-collection-pop.styl
  src/components/collections-list/index.js
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/containers/visually-hidden.js
  src/components/popover/index.js
  src/components/popover/search.js
  src/components/popover/styles.styl
  src/components/profile-list/index.js
  src/components/project/add-project-to-collection-pop.js
  src/components/project/popover.styl
  src/components/project/project-embed.js
  src/components/project/project-embed.styl
  src/components/project/project-item.js
  src/components/project/project-options-pop.js
  src/presenters/includes/collection-result-item.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/project-options-pop.js
  src/state/search.js
  src/state/segment-analytics.js
Labels: Waiting on Reviews

#604 Long museum: collection avatar a11y improvement
  src/components/collection/defaultAvatar.js
  src/components/link/index.js
  src/presenters/includes/collection-avatar.js
Labels: Ready to merge

#602 Chain cut: handle teams without urls
  src/components/search-results/index.js
  src/state/search.js
Labels: Ready to merge

#605 Plump tern: Team User Info popover
  src/.eslintrc.js
  src/components/team-users/index.js
  src/components/team-users/styles.styl
  src/components/team-users/team-user-info.js
  src/curated/collections.js
  src/curated/featured.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
  styles/pop-overs.styl
Labels: Under Review

#598 Fifth reaction: Replace Default User & Team Cover Image
  .glitch-assets
  src/components/search-result-cover-bar/index.js
  src/models/team.js
  src/models/user.js
  src/presenters/includes/collection-avatar.js
Labels: Ready to merge

#601 Onyx text: componentize team analytics
  src/components/buttons/button.styl
  src/components/containers/results-list.js
  src/components/containers/results-list.styl
  src/components/project/project-result-item.js
  src/components/team-analytics/index.js
  src/components/team-analytics/styles.styl
  src/components/team-analytics/team-analytics-activity.js
  src/components/team-analytics/team-analytics-project-details.js
  src/components/team-analytics/team-analytics-project-pop.js
  src/components/team-analytics/team-analytics-referrers.js
  src/components/team-analytics/team-analytics-summary.js
  src/components/team-analytics/team-analytics-time-pop.js
  src/presenters/includes/project-result-item.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-analytics-referrers.js
  src/presenters/includes/team-analytics-summary.js
  src/presenters/includes/team-analytics.js
  src/presenters/pages/team.js
  src/presenters/pages/team.styl
  src/presenters/pop-overs/team-analytics-project-pop.js
  src/presenters/pop-overs/team-analytics-time-pop.js
  src/state/api.js
  styles/includes/team-analytics.styl
  styles/styles.styl
Labels: Ready to merge

#599 delicious-pulsar: Move notifications provider to src/state, componentize notifications
  src/app.js
  src/components/collection/add-collection-project-pop.js
  src/components/collection/create-collection-pop.js
  src/components/collections-list/index.js
  src/components/notification/index.js
  src/components/notification/styles.styl
  src/components/project/add-project-to-collection-pop.js
  src/components/report-abuse-pop/index.js
  src/components/report-abuse-pop/styles.styl
  src/components/sign-in-pop/index.js
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
  src/components/team/delete-team-pop.js
  src/models/collection.js
  src/presenters/error-handlers.js
  src/presenters/includes/name-conflict.js
  src/presenters/includes/uploader.js
  src/presenters/notifications.js
  src/presenters/pages/join-team.js
  src/presenters/pages/sign-in.js
  src/presenters/team-editor.js
  src/state/notifications.js
  src/state/offline-notice.js
  stories/index.js
  styles/includes/notifications.styl
  styles/pop-overs.styl
  styles/progress.styl
  styles/styles.styl
Labels: Ready to merge

#611 Clover bead: componentize ProjectAvatar
  src/components/header/new-project-pop.js
  src/components/images/avatar.js
  src/components/project/add-project-to-collection-pop.js
  src/components/project/project-result-item.js
  src/components/search-form/autocomplete.js
  src/components/team-analytics/team-analytics-project-details.js
  src/components/team-users/team-user-info.js
  src/presenters/includes/project-avatar.js
Labels: Ready to merge

#609 Foggy camera: inline TeamMarketing into teams page
  src/presenters/includes/team-elements.js
  src/presenters/pages/team.js
  src/presenters/pages/team.styl
  styles/icons.styl
Labels: Ready to merge

#614 sequoia-click: "Remove from Team" to "Leave Team" if is the current user
  src/components/team-users/team-user-info.js
Labels: Ready to merge

#612 Coordinated cauliflower: collection item button
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
Labels: Waiting on Reviews

#576 Superb guide: collection reorder prompt + minor css cleanup + empty collection fixes
  src/components/containers/grid.js
  src/components/containers/grid.styl
  src/components/containers/projects-list.styl
  src/presenters/collection-editor.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
Labels: Under Review

#615 Lunar front 1: add accessible label to user profile link in recent projects
  src/components/recent-projects/index.js
Labels: Waiting on Reviews

#616 Chip petalite: consolidate links on featured embed
  src/presenters/featured-embed.js
  styles/includes/featured.styl
Labels: Waiting on Reviews

#610 Humdrum triangle: VS Code auth page
  src/components/popover/dialog.js
  src/components/sign-in-pop/index.js
  src/presenters/pages/router.js
  src/presenters/pages/vscode-auth.js
  src/presenters/pages/vscode-auth.styl
Labels: Ready to merge

#620 automatic-hacksaw: fix team-user-info avatar link and hover state
  src/components/team-users/team-user-info.js
Labels: Ready to merge

#595 Pool sweatpants: resend invites for team users, delete invited user
  src/components/team-users/index.js
  src/components/team-users/styles.styl
  stories/index.js
Labels: Under Review

#607 Nova chance: Fix the project is still building page
  server/webpack.js
  webpack.config.js
Labels: Waiting on Reviews

#622 witty-prawn: a whole bunch of button fixes
  src/components/buttons/button.js
  src/components/buttons/button.styl
  src/components/collection/edit-collection-color-pop.js
  src/components/footer/footer.styl
  src/components/images/emoji.styl
  src/components/popover/index.js
  src/components/project/add-project-to-collection-pop.js
  src/components/project/featured-project.js
  src/components/project/project-item.js
  src/components/recent-projects/index.js
  src/components/sign-in-pop/index.js
  src/components/team-users/index.js
  src/components/team/add-team-project-pop.js
  src/components/team/delete-team-pop.js
  src/presenters/includes/project-actions.js
  src/presenters/overlays/new-stuff.js
  src/presenters/pages/collection.js
  src/presenters/pages/index.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/user-options-pop.js
  stories/index.js
  styles/projects.styl
Labels: Under Review

#630 fourth-crate: quick fix to buttons in team-users
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
Labels: Waiting on Reviews

#619 Loud roadrunner: hookify user editor
  src/presenters/pages/user.js
  src/presenters/user-editor.js
  src/state/user.js
Labels: Ready to merge

#618 Petalite pot: hookify teams page
  src/presenters/pages/team.js
  src/presenters/team-editor.js
  src/state/team.js
Labels: Ready to merge

#626 Honored innocent: componentize layout
  src/components/layout/index.js
  src/components/layout/styles.styl
  src/presenters/includes/konami.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/error.js
  src/presenters/pages/index.js
  src/presenters/pages/project.js
  src/presenters/pages/questions.js
  src/presenters/pages/search.js
  src/presenters/pages/team-or-user.js
  styles/globals.styl
Labels: Under Review

#629 Sudden kick: componentize much of `/includes`
  src/app.js
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-result-item.js
  src/components/collection/note.js
  src/components/error-boundary.js
  src/components/fields/auth-description.js
  src/components/images/avatar.js
  src/components/layout/index.js
  src/components/project/project-actions.js
  src/components/project/project-embed.js
  src/components/questions/index.js
  src/components/search-form/autocomplete.js
  src/components/search-result-cover-bar/index.js
  src/presenters/featured-collections.js
  src/presenters/includes/collection-avatar.js
  src/presenters/includes/name-conflict.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/project-editor.js
  src/state/team.js
  src/state/uploader.js
  src/state/user.js
  src/utils/color.js
Labels: Ready to merge

#624 Fifth turret: hookify project editor
  src/models/project.js
  src/presenters/pages/project.js
  src/presenters/project-editor.js
  src/state/api.js
  src/state/project.js
Labels: Ready to merge

#628 Storm scene: miscellaneous popover componentizations
  src/components/popover/container.js
  src/components/search-form/index.js
  src/components/team/delete-team-pop.js
  src/presenters/overlays/overlay-video.js
  src/presenters/pages/project.js
  src/presenters/pages/router.js
  src/presenters/pages/sign-in.js
Labels: Under Review

#631 weak-sale: componentize user options pop and create team pop
  src/components/create-team-pop/index.js
  src/components/create-team-pop/styles.styl
  src/components/header/header.styl
  src/components/header/index.js
  src/components/user-options-pop/index.js
  src/components/user-options-pop/styles.styl
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/popover-button.js
  src/presenters/pop-overs/popover-with-button.js
  styles/pop-overs.styl
Labels: Ready to merge

#632 Glittery thief: componentize project description expander
  src/components/containers/expander.js
  src/components/containers/expander.styl
  src/presenters/includes/expander.js
  src/presenters/pages/project.js
  styles/includes/expander.styl
  styles/styles.styl
Labels: Waiting on Reviews

#627 Sugary anthropology: componentize new stuff modal
  src/components/layout/index.js
  src/components/new-stuff/index.js
  src/components/new-stuff/styles.styl
  src/components/overlays/index.js
  src/components/overlays/overlays.styl
  src/presenters/includes/collection-avatar.js
  styles/new-stuff.styl
  styles/styles.styl
Labels: Ready to merge

#606 mighty-queen: Update packages in package.json to newest versions
  package.json
  shrinkwrap.yaml
  src/state/api.js
  src/state/current-user.js
  webpack.config.js
Labels: Ready to merge

#637 Encouraging girdle: fix bug in search bar results
  src/components/popover/container.js
  src/components/search-form/index.js
  src/presenters/overlays/overlay-video.js
Labels: Ready to merge

#639 Nova-chance: Fix a bug with project restarts
  webpack.config.js
Labels: Waiting on Reviews

#625 Lime hawthorn: hookify collection editor
  src/presenters/collection-editor.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/state/collection.js
Labels: Ready to merge

#623 Mirage power 1: replace ProjectsLoader with project context
  src/app.js
  src/components/containers/projects-list.js
  src/components/project/project-item.js
  src/components/project/project-options-pop.js
  src/components/project/project-result-item.js
  src/components/recent-projects/index.js
  src/components/related-projects/index.js
  src/components/search-results/index.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/projects-loader.js
  src/state/current-user.js
  src/state/project.js
  src/state/search.js
  src/state/team.js
Labels: Ready to merge

#635 Quixotic rocket: Deleted a ton of old css that isn't used anywhere
  src/components/collection/note.styl
  src/components/inputs/text-area.styl
  src/components/recent-projects/styles.styl
  src/components/report-abuse-pop/index.js
  src/components/report-abuse-pop/styles.styl
  styles/buttons.styl
  styles/collections.styl
  styles/globals.styl
  styles/inputs.styl
  styles/pages/category.styl
  styles/pages/collection.styl
  styles/pages/questions.styl
  styles/pop-overs.styl
  styles/profile.styl
  styles/projects.styl
  styles/styles.styl
Labels: Ready to merge

#640 Electric check: clear out old popovers
  src/components/collection/create-collection-pop.js
  src/components/collection/create-collection-pop.styl
  src/presenters/pop-overs/dropdown.js
  src/presenters/pop-overs/popover-container.js
  src/presenters/pop-overs/popover-nested.js
  styles/dropdowns.styl
  styles/new-stuff.styl
  styles/pop-overs.styl
  styles/styles.styl
Labels: Ready to merge

#643 Worried girl: modularize /secret styles
  src/presenters/pages/secret.js
  src/presenters/pages/secret.styl
  styles/pages/secret.styl
  styles/styles.styl
Labels: Ready to merge

#641 Caterwauling gemini: move error-handlers to state dir
  src/state/collection.js
  src/state/error-handlers.js
  src/state/project.js
  src/state/search.js
  src/state/team.js
  src/state/user.js
Labels: Ready to merge

#634 Cassey-community: fix img HTML issues in magikarp on no js page & parsing errors on a project page
  src/components/buttons/button.js
  src/components/collection/collection-item.js
  src/components/collection/defaultAvatar.js
  src/components/header/header.styl
  src/components/inputs/markdown-input.styl
  src/components/project/embed.js
  src/components/project/project-embed.js
  src/components/project/project-embed.styl
  src/components/text/markdown.js
  src/components/user-options-pop/index.js
  views/index.ejs
Labels: Ready to merge

#651 Second okra: fix invite bug
  src/state/team.js
Labels: Waiting on Reviews

#633 Like story: Clarify error states on optimistic input fields
  src/components/fields/optimistic-markdown-input.js
  src/components/fields/optimistic-text-input.js
  src/components/fields/optimistic-wrapping-text-input.js
  src/components/fields/use-optimistic-text.js
  src/components/fields/use-optimistic-value.js
  src/components/fields/use-passively-trimmed-input.js
Labels: Under Review

#647 Pool brownie: modularize project page styles
  src/presenters/pages/project.js
  src/presenters/pages/project.styl
  styles/pages/project.styl
  styles/styles.styl
Labels: Ready to merge

#656 Chestnut cappelletti 1: Add OAuth page back
  src/presenters/pages/router.js
  src/presenters/pages/signin.js
  src/presenters/pages/signin.styl
Labels: Ready to merge

#652 sedate-pancreas-1: add polyfill for intersection observer
  package.json
  shrinkwrap.yaml
  src/polyfills.js
Labels: Ready to merge

#648 Pentagonal save: modularize error pages
  src/presenters/pages/error.js
  src/presenters/pages/error.styl
  src/presenters/pages/router.js
  styles/globals.styl
  styles/pages/error.styl
  styles/styles.styl
Labels: Ready to merge

#661 various-session: reduce specificity of heading styles and refactor Heading to accept className
  .glitch-assets
  src/components/text/heading.js
  src/components/text/heading.styl
Labels: Waiting on Reviews

#649 Truth wound: more style removal
  src/components/project/project-item.styl
  styles/animations.styl
  styles/buttons.styl
  styles/emoji.styl
  styles/includes/featured.styl
  styles/profile.styl
  styles/projects.styl
  styles/results-list.styl
  styles/styles.styl
Labels: Ready to merge

#664 Melted scorpion: fix show all bug
  src/components/containers/projects-list.js
Labels: Waiting on Reviews

#663 Quixotic-rocket: Replace _cacheCover with updatedAt
  src/components/containers/cover-container.js
  src/components/containers/profile/team.js
  src/state/team.js
  src/state/user.js
Labels: Waiting on Reviews

#666 Useful bangle: fix small collection item styles
  src/components/collection/collection-item.styl
Labels: Ready to merge

#645 Plump clave: combine collection, category, featured collection into single component
  src/components/collection/collection-item.styl
  src/components/collection/container.js
  src/components/collection/container.styl
  src/components/project/featured-project.js
  src/components/project/project-embed.js
  src/models/collection.js
  src/presenters/featured-collections.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/router.js
  styles/collections.styl
  styles/pages/collection.styl
  styles/styles.styl
Labels: Waiting on Reviews

#671 Quixotic-rocket: Fix create collection on team pages with a space in their name
  src/components/collection/create-collection-pop.js
Labels: Waiting on Reviews

#665 Sweet line: collection projects cache
  src/app.js
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-result-item.js
  src/components/collection/container.js
  src/components/collections-list/more-collections.js
  src/components/search-results/index.js
  src/components/team/team-item.js
  src/presenters/featured-collections.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/router.js
  src/presenters/pages/team.js
  src/state/collection.js
  src/state/search.js
  src/state/team.js
  src/state/user.js
Labels: Under Review

#672 aromatic-mushroom: add size prop to TeamAvatar
  src/components/images/avatar.js
Labels: Waiting on Reviews

#668 Melted scorpion: toBlob support for edge
  src/polyfills.js
Labels: Ready to merge

#673 Regular muscle: show user avatars on collection notes
  src/components/collection/collection-item.js
  src/components/collection/note.js
Labels: Waiting on Reviews

#676 solid-revolve: cover images shouldn't repeat if user has uploaded an image
  src/components/containers/cover-container.js
  src/components/containers/cover-container.styl
Labels: Waiting on Reviews

#675 Vivacious shirt: Fix /vscode-auth multi-prompt
  src/presenters/pages/vscode-auth.js
Labels: Under Review

#667 Harmonious memory: standardize/centralize API calls
  src/components/collection/note.js
  src/components/collections-list/index.js
  src/components/deleted-projects/index.js
  src/components/project/featured-project.js
  src/components/project/project-item.js
  src/components/project/project-options-pop.js
  src/components/search-results/index.js
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
  src/components/team/delete-team-pop.js
  src/state/api.js
  src/state/collection.js
  src/state/project.js
  src/state/team.js
  src/state/user.js
  src/utils/assets.js
Labels: Waiting on Reviews

#589 tundra-beat: Two-Factor Authentication
  .glitch-assets
  TESTING.md
  cypress/integration/header_actions/accountSettings.js
  cypress/integration/header_actions/signIn.js
  cypress/support/commands.js
  package.json
  shared/aliases.js
  shrinkwrap.yaml
  src/components/account-settings-overlay/index.js
  src/components/account-settings-overlay/password-settings.js
  src/components/account-settings-overlay/styles.styl
  src/components/account-settings-overlay/two-factor-settings.js
  src/components/buttons/button.js
  src/components/buttons/sign-in-button.js
  src/components/header/index.js
  src/components/images/emoji.js
  src/components/inputs/text-input.js
  src/components/layout/auth-layout.js
  src/components/layout/auth-layout.styl
  src/components/layout/index.js
  src/components/new-password-input/index.js
  src/components/new-password-input/new-password-input.styl
  src/components/new-password-input/password-strength.js
  src/components/new-password-input/password-strength.styl
  src/components/new-stuff/index.js
  src/components/recent-projects/index.js
  src/components/sign-in-pop/index.js
  src/components/sign-in/styles.styl
  src/components/sign-in/two-factor-form.js
  src/components/user-options-pop/index.js
  src/presenters/pages/login.js
  src/presenters/pages/reset-password.js
  src/presenters/pages/reset-password.styl
  src/presenters/pages/router.js
  src/presenters/pages/two-factor-code.js
  src/presenters/pages/vscode-auth.styl
  src/state/current-user.js
  src/state/dev-toggles.js
  styles/overlays.styl
Labels: Under Review
