Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-10, with the labels that each got.

#942 Vivacious lychee: pupdates fixes
  server/curated.js
  server/render.js
  server/routes.js
  src/client.js
  src/components/new-stuff/index.js
  src/components/overlays/overlays.styl
  src/presenters/pages/pupdates-preview.js
  src/server.js
  src/state/globals.js
  views/index.ejs
Labels: Waiting on Reviews

#943 Intelligent dumpling: fix nested link
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#944 Sedate cheese: toggle 'create collection' popover when submitting
  src/components/project/project-options-pop.js
Labels: Ready to merge

#887 Quartz church: TextInput and TextArea components
  src/components/account-settings-overlay/password-settings.js
  src/components/account-settings-overlay/two-factor-settings.js
  src/components/collection/create-collection-pop.js
  src/components/collection/edit-collection-color-pop.js
  src/components/create-team-pop/index.js
  src/components/fields/collection-name-input.js
  src/components/fields/optimistic-text-input.js
  src/components/fields/team-fields.js
  src/components/fields/user-login-input.js
  src/components/fields/user-name-input.js
  src/components/filter-controller/index.js
  src/components/inputs/input-error-icon.js
  src/components/inputs/input-error-message.js
  src/components/inputs/input-error-message.styl
  src/components/inputs/markdown-input.js
  src/components/inputs/text-area.js
  src/components/inputs/text-area.styl
  src/components/inputs/text-input.js
  src/components/inputs/text-input.styl
  src/components/inputs/wrapping-text-input.js
  src/components/new-password-input/index.js
  src/components/popover/search.js
  src/components/report-abuse-pop/index.js
  src/components/search-form/index.js
  src/components/search-form/search-form.styl
  src/components/sign-in-pop/index.js
  src/components/sign-in/get-magic-code.js
  src/components/sign-in/two-factor-form.js
  src/components/sign-in/use-magic-code.js
  src/presenters/pages/project.js
Labels: Ready to merge

#939 Functional politician: Update Handraise Icon
  .glitch-assets
  src/components/collection/collection-avatar.js
  src/components/questions/index.js
  src/components/questions/item.js
Labels: Ready to merge

#946 Comfortable buzzard: fix notification button styles
  src/app.js
Labels: Ready to merge

#938 Quixotic-rocket: Increased memory limit for node
  package.json
Labels: Ready to merge

#953 Show Category Avatar instead of generated avatar
  src/components/collection/container.js
Labels: Ready to merge

#930 spectacular-coyote: fix onboarding banner logic on profile pages
  src/presenters/pages/user.js
Labels: Under Review

#954 Invented Catsup: Fix small my stuff bug
  src/models/collection.js
Labels: Ready to merge

#929 Romantic broom: fixed ratio containers for large videos on create page
  src/presenters/pages/create.js
Labels: Ready to merge

#948 Warm fossa: make internal button links use react-router
  src/components/team/team-item.js
  src/components/user-options-pop/index.js
  src/presenters/pages/create.js
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/team.js
Labels: Ready to merge

#952 Fallacious slice: Fix ssr getting stuck after failing to load the client code
  server/render.js
Labels: Ready to merge

#949 Sour maize: update recent projects when leaving a project
  src/state/current-user.js
  src/state/project-options.js
Labels: Ready to merge

#945 Simple wildebeest: Add a loader to the super user checkbox
  src/components/user-options-pop/index.js
  src/state/current-user.js
Labels: Ready to merge

#957 Proximal yarn: handle 404 for /user/:id routes
  src/presenters/pages/team-or-user.js
Labels: Waiting on Reviews

#955 circular-passionfruit: Remove "Resume Coding" button and add "Edit Project" to recent projects project items
  src/components/containers/projects-list.js
  src/components/header/index.js
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/components/recent-projects/index.js
Labels: Ready to merge

#959 Fix bugs for My Stuff and Private Collections, mostly a11y issues
  src/components/buttons/bookmark-button.js
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/collection/collection-result-item.js
  src/components/collection/collection-result-item.styl
  src/components/private-badge/index.js
  src/components/private-badge/styles.styl
Labels: Waiting on Reviews

#962 Set pnpm to 3.x
  .circleci/config.yml
Labels: Ready to merge

#966 Profuse tea: Update sentry to the latest version
  .glitch-assets
  package.json
  shared/api.js
  shrinkwrap.yaml
Labels: Ready to merge

#967 Profuse-tea: Call the sentry init code in production builds
  package.json
Labels: Waiting on Reviews

#934 Occipital point: Signin with User Passwords, add Forgot Password
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
  src/components/sign-in-pop/index.js
  src/components/sign-in/forgot-password.js
  src/components/sign-in/sign-in-with-password.js
  src/components/sign-in/styles.styl
  src/components/sign-in/use-magic-code.js
Labels: Ready to merge

#932 Superb guide: SSR all pages, move seo into react code
  package.json
  server/routes.js
  shared/regex.js
  shrinkwrap.yaml
  src/app.js
  src/components/containers/profile/project.js
  src/components/glitch-helmet/index.js
  src/components/layout/index.js
  src/components/text/markdown.js
  src/models/collection.js
  src/models/project.js
  src/presenters/pages/about/about-layout.js
  src/presenters/pages/collection.js
  src/presenters/pages/create.js
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/project.js
  src/presenters/pages/secret.js
  src/presenters/pages/team-or-user.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/utils/constants.js
  src/utils/markdown.js
  views/index.ejs
Labels: Ready to merge

#974 woozy-damselfly: fix issue with removing a project from My Stuff after creation
  src/state/collection.js
  src/state/project-options.js
Labels: Waiting on Reviews

#947 Nova chance: Preload optimizely config, track optimizely in react
  server/optimizely.js
  server/render.js
  server/routes.js
  shared/constants.js
  src/client.js
  src/components/team-analytics/index.js
  src/server.js
  src/state/rollout-toggles.js
  src/state/rollouts.js
  src/utils/constants.js
  views/index.ejs
Labels: Ready to merge

#956 Various dart: search styling fix
  src/components/collection/edit-collection-color-pop.js
  src/components/collection/edit-collection-color-pop.styl
  src/components/filter-controller/index.js
  src/components/filter-controller/styles.styl
  src/components/popover/search.js
  src/components/popover/styles.styl
  src/components/search-form/index.js
  src/components/search-form/search-form.styl
Labels: Ready to merge

#963 Fallacious slice: Rename the DEPLOY_ENV var to BUILD_TYPE
  README.md
  STYLE.md
  aliases.js
  package.json
  server/render.js
  server/webpack.js
Labels: Ready to merge

#975 Humdrum triangle: 2FA form for new auth flow
  src/components/containers/preview-container.styl
  src/components/layout/auth-layout.js
  src/components/layout/auth-layout.styl
  src/components/layout/multi-page.js
  src/components/layout/sign-in-layout.js
  src/components/layout/sign-in-layout.styl
  src/components/overlays/index.js
  src/components/overlays/overlays.styl
  src/components/sign-in-pop/index.js
  src/components/sign-in/two-factor-form.js
  src/components/sign-in/use-magic-code.js
  src/presenters/pages/login/callbacks.js
  src/presenters/pages/login/reset-password.js
  src/presenters/pages/login/reset-password.styl
  src/presenters/pages/login/styles.styl
  src/presenters/pages/login/two-factor-code.js
  src/presenters/pages/two-factor-code.js
Labels: Ready to merge

#984 Fix tests & add more & a11y fix
  package.json
  src/components/buttons/bookmark-button.js
  src/components/private-badge/index.js
  test/components/private-badge.js
  test/setup.js
Labels: Ready to merge

#973 harmless-path: Update homepage + pupdates to handle rich text content and update /{page}/preview to show drafts from new CMS
  README.md
  package.json
  server/routes.js
  shrinkwrap.yaml
  src/components/containers/preview-container.js
  src/components/data-loader/index.js
  src/components/new-stuff/new-stuff-article.js
  src/curated/home.json
  src/curated/pupdates.json
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/home-v2/styles.styl
  src/presenters/pages/pupdates-preview.js
Labels: Ready to merge

#976 Ancient salmonberry: Convert Categories to Collections
  .glitch-assets
  server/routes.js
  shared/categories.js
  src/components/categories-grid/index.js
  src/components/more-ideas/index.js
  src/components/more-ideas/more-ideas.styl
  src/components/onboarding-banner/index.js
  src/curated/categories.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/create.js
  src/presenters/pages/router.js
Labels: Ready to merge

#982 Cleanup: Remove integration test build step
  .circleci/config.yml
Labels: Ready to merge

#990 Profuse-tea: Filter optimizely network errors out of sentry
  shared/sentryHelpers.js
Labels: Ready to merge

#991 Humdrum-triangle: Add 2fa toggle
  shrinkwrap.yaml
  src/components/account-settings-overlay/index.js
  src/components/account-settings-overlay/password-settings.js
  src/components/account-settings-overlay/styles.styl
  src/state/dev-toggles.js
Labels: Ready to merge

#988 Ivy crib: Fix/Update Analytics Events
  src/components/collection/container.js
  src/components/project/featured-project.js
  src/components/project/project-actions.js
  src/components/project/project-item.js
  src/presenters/pages/project.js
Labels: Waiting on Reviews

#1003 Airy ranunculus: port questions to use v1 API
  src/components/questions/index.js
Labels: Ready to merge

#1006 Add "resume coding" to home page
  src/components/header/index.js
Labels: Ready to merge

#1004 Humdrum-triangle: Add reset password from email
  src/presenters/pages/login/reset-password.js
Labels: Under Review

#985 Nova chance: Disable cloudfront caching of html
  server/routes.js
Labels: Under Review

#995 Fallacious slice: fix two small bugs I found
  src/presenters/pages/router.js
  src/state/ab-tests.js
  src/state/current-user.js
Labels: Under Review

#1013 Fix homepage bug
  src/presenters/pages/home-v2/index.js
Labels: Ready to merge

#1012 Profuse tea: Fix project page flicker, one path for 404 errors
  src/components/related-projects/index.js
  src/state/project.js
Labels: Ready to merge

#1016 Profuse tea: Fix ssr project pages
  .glitch-assets
  src/components/project/project-actions.js
Labels: Ready to merge

#1015 Glowing draw: Update Embed to optionally point directly to project
  src/components/profile-list/index.js
  src/components/project/embed.js
  src/components/project/embed.styl
  src/components/project/featured-project.js
  src/components/project/project-embed.js
  src/components/project/project-embed.styl
Labels: Ready to merge

#936 Nosy-provelone: mobile UI fixes
  src/components/collection/collection-item.styl
  src/components/containers/projects-list.styl
  src/components/layout/styles.styl
  src/components/project/project-item.styl
Labels: Ready to merge

#1021 Profuse tea: Fix join project button flicker, increase some timeouts
  server/api.js
  shrinkwrap.yaml
  src/client.js
  src/components/project/project-embed.js
  src/presenters/pages/project.js
  src/state/project-options.js
Labels: Ready to merge

#1022 Fallacious slice: Don't load stuff right away, wait until it's relevant
  src/components/project/project-item.js
  src/components/team-users/team-user-info.js
  src/components/visibility-container/index.js
  src/state/project-options.js
  src/state/project.js
Labels: Waiting on Reviews

#958 Cookie ricotta: POPOVERS, componentized
  package.json
  shrinkwrap.yaml
  src/components/collection/add-collection-project-pop.js
  src/components/collection/collection-options-pop.js
  src/components/collection/create-collection-pop.js
  src/components/collection/delete-collection-pop.js
  src/components/collection/edit-collection-color-pop.js
  src/components/collection/edit-collection-color-pop.styl
  src/components/create-team-pop/index.js
  src/components/create-team-pop/styles.styl
  src/components/global.styl
  src/components/images/avatar.styl
  src/components/new-project-pop/index.js
  src/components/popover/base.js
  src/components/popover/dialog.js
  src/components/popover/index.js
  src/components/popover/search.js
  src/components/popover/styles.styl
  src/components/project/add-project-to-collection-pop.js
  src/components/project/featured-project-options-pop.js
  src/components/project/featured-project.styl
  src/components/project/leave-project-pop.js
  src/components/project/popover.styl
  src/components/project/project-actions.js
  src/components/project/project-options-pop.js
  src/components/report-abuse-pop/index.js
  src/components/sign-in-pop/index.js
  src/components/team-analytics/styles.styl
  src/components/team-analytics/team-analytics-project-pop.js
  src/components/team-analytics/team-analytics-time-pop.js
  src/components/team-users/add-team-user.js
  src/components/team-users/index.js
  src/components/team-users/team-user-info.js
  src/components/team/add-team-project-pop.js
  src/components/team/delete-team-pop.js
  src/components/user-options-pop/index.js
  src/components/user-options-pop/styles.styl
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/signin.js
Labels: Under Review

#1023 Thinkable gold - Change Add to Collection Button Project Pages
  src/components/onboarding-banner/index.js
  src/components/project/add-project-to-collection-pop.js
  src/components/project/project-actions.js
  src/components/video/index.js
  src/hooks/use-window-size.js
Labels: Ready to merge

#1027 Fallacious slice: Filter out some optimizely errors, rate limit rate limit errors
  src/client.js
  src/utils/sentry.js
Labels: Ready to merge

#1036 Profuse tea: Fix project items with links in their description
  src/components/images/avatar.js
  src/components/images/avatar.styl
  src/components/profile-list/index.js
  src/components/project/project-item.js
  src/components/text/markdown.js
  src/utils/markdown.js
Labels: Ready to merge

#1029 Nova chance: Clean up ssr context handling
  server/api.js
  server/render.js
  server/routes.js
  views/index.ejs
Labels: Ready to merge

#1041 Checkered-fifth: Fix missing backgrounds on logged out homepage feature callouts
  src/presenters/pages/home-v2/index.js
Labels: Waiting on Reviews
