Repository glitchdotcom/Glitch-Community, pull requests merged in 2019-04, with the labels that each got.

#393 Cedar deal: fix collection UI overflow
  src/presenters/collection-item.js
  styles/collections.styl
Labels: Waiting on Reviews

#399 Clover socks: componentize user & team items
  src/components/blocks/search-result-cover-bar.js
  src/components/blocks/search-result-cover-bar.styl
  src/components/blocks/thanks.js
  src/components/blocks/thanks.styl
  src/components/collection/collection-item.styl
  src/components/project/project-item.styl
  src/components/team/team-item.js
  src/components/team/team-item.styl
  src/components/user/user-item.js
  src/components/user/user-item.styl
  src/components/user/users-list.styl
  src/presenters/pages/search.js
  stories/index.js
Labels: Waiting on Reviews

#405 Stingy print: store active search filter in query params
  src/presenters/pages/router.js
  src/presenters/pages/search.js
Labels: Waiting on Reviews

#394 Sunset stitch: Super User Banner and Toggle Button
  src/app.js
  src/presenters/overlays/super-user-banner.js
Labels: Waiting on Reviews

#398 Garrulous literature: show top results on search page
  src/components/errors/not-found.js
  src/components/errors/not-found.styl
  src/components/loaders/loader.js
  src/components/loaders/loader.styl
  src/components/project/project-item.styl
  src/components/search/autocomplete.js
  src/components/search/form.js
  src/components/search/form.styl
  src/components/search/search-results.js
  src/components/search/search-results.styl
  src/presenters/collection-item.js
  src/presenters/collections-list.js
  src/presenters/deleted-projects.js
  src/presenters/includes/loader.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-analytics.js
  src/presenters/pages/collection.js
  src/presenters/pages/error.js
  src/presenters/pages/project.js
  src/presenters/pages/router.js
  src/presenters/pages/search.js
  src/presenters/pages/team-or-user.js
  src/presenters/pop-overs/add-collection-project-pop.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/delete-team-pop.js
  src/presenters/pop-overs/new-project-pop.js
  src/presenters/pop-overs/report-abuse-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
  src/presenters/recent-projects.js
  src/state/search.js
  stories/index.js
  styles/animations.styl
  styles/collections.styl
  styles/globals.styl
  styles/loader.styl
  styles/pages/error.styl
  styles/pages/search.styl
  styles/projects.styl
  styles/styles.styl
Labels: Waiting on Reviews

#404 Iris okapi: Update email sign in to have consistent error styles
  src/presenters/pop-overs/sign-in-pop.js
Labels: Ready to merge

#409 Melodious fifth: make algolia search fully usable
  src/components/blocks/search-result-cover-bar.js
  src/components/blocks/search-result-cover-bar.styl
  src/components/collection/small-collection-item.js
  src/components/images/avatar.js
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/components/search/autocomplete.js
  src/components/search/search-results.js
  src/components/search/search-results.styl
  src/components/team/team-item.js
  src/components/user/user-item.js
  src/components/user/users-list.js
  src/components/user/users-list.styl
  src/state/search.js
  stories/index.js
  styles/includes/header.styl
Labels: Waiting on Reviews

#414 Nova chance: Fix a regression with anon user avatars, use the avatar component everywhere
  src/components/images/avatar.js
  src/components/images/image.js
  src/components/search/autocomplete.js
  src/components/user/user-item.js
  src/presenters/collection-item.js
  src/presenters/featured-collections.js
  src/presenters/includes/avatar.js
  src/presenters/includes/collection-result-item.js
  src/presenters/includes/project-result-item.js
  src/presenters/includes/team-users.js
  src/presenters/pages/project.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/teams-list.js
  src/presenters/users-list.js
Labels: Waiting on Reviews

#419 Cheerful flamingo: use "Thanks" component everywhere
  src/components/blocks/thanks.styl
  src/presenters/includes/thanks.js
  src/presenters/includes/user-result-item.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/team-user-info-pop.js
Labels: Under Review

#416 Organic dance: UI Tweaks to Team Analytics
  src/components/buttons/segmented-buttons.js
  src/components/buttons/segmented-buttons.styl
  src/presenters/includes/team-analytics-activity.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-analytics-referrers.js
  src/presenters/includes/team-analytics-summary.js
  src/presenters/includes/team-analytics.js
  src/presenters/pop-overs/team-analytics-project-pop.js
  src/presenters/pop-overs/team-analytics-time-pop.js
  styles/c3.styl
  styles/globals.styl
  styles/includes/team-analytics.styl
Labels: Ready to merge

#427 Stitch close: no, actually fix the search page under algolia
  src/components/search/search-results.js
  src/components/user/users-list.js
  src/curated/collections.js
  src/curated/featured-embed.js
Labels: Ready to merge

#430 Statuesque father: remove `notSafeForKids` items from algolia search
  src/state/search.js
Labels: Ready to merge

#422 Reflective ship: use project item component everywhere
  src/components/containers/projects-list.js
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/presenters/pages/collection.js
  src/presenters/project-item.js
  src/presenters/team-item.js
  src/presenters/user-item.js
  styles/note.styl
  styles/pages/collection.styl
  styles/projects.styl
Labels: Ready to merge

#435 Chipped bangle: Changes to filename hashes for bundles
  package.json
  shrinkwrap.yaml
  webpack.config.js
Labels: Waiting on Reviews

#437 Quixotic rocket: Lots of refactors and fixes for server code + forever
  .gitignore
  package.json
  server/api.js
  server/proxy.js
  server/server.js
  shared/sentryHelpers.js
  shrinkwrap.yaml
Labels: Waiting on Reviews

#421 Ambiguous map: CoverContainer
  server/api.js
  src/components/containers/cover-container.js
  src/components/containers/cover-container.styl
  src/presenters/includes/profile.js
  src/presenters/includes/related-projects.js
  src/presenters/more-collections.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/recent-projects.js
  stories/index.js
  styles/pages/user-and-team-page.styl
  styles/profile.styl
Labels: Ready to merge

#440 Apple tang: bring back notes to the homepage
  src/components/containers/projects-list.js
  src/components/project/project-item.styl
  src/presenters/collection-editor.js
  src/presenters/featured-collections.js
  src/presenters/note.js
  src/presenters/pages/collection.js
  stories/index.js
  styles/includes/featured.styl
  styles/note.styl
  styles/pages/user-and-team-page.styl
Labels: Ready to merge

#445 loud-cockroach: open new project popover from the right
  styles/pop-overs.styl
Labels: Ready to merge

#444 Bead-Walrus: fix z-index for dropdowns
  src/components/project/project-item.styl
Labels: Ready to merge

#411 Zest ostrich: Feature a Project Embed in Collections
  src/components/project/featured-project.js
  src/components/project/featured-project.styl
  src/components/project/project-embed.js
  src/components/project/project-embed.styl
  src/curated/collections.js
  src/presenters/collection-editor.js
  src/presenters/entity-page-projects.js
  src/presenters/note.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/featured-project-options-pop.js
  src/presenters/pop-overs/project-options-pop.js
  styles/animations.styl
  styles/collections.styl
  styles/deleted-projects.styl
  styles/note.styl
  styles/pages/collection.styl
  styles/pages/project.styl
  styles/pages/user-and-team-page.styl
  styles/profile.styl
  styles/projects.styl
Labels: Ready to merge

#434 Outstanding tree: keyboard navigation for autocomplete results
  src/components/inputs/text-input.js
  src/components/search/autocomplete.js
  src/components/search/autocomplete.styl
  src/components/search/form.js
  src/components/search/form.styl
  src/state/search.js
Labels: Waiting on Reviews

#433 Profuse tea: Render pending team invites outside of the add user popover container
  server/webpack.js
  src/presenters/includes/team-users.js
  src/presenters/pop-overs/popover-container.js
  src/presenters/pop-overs/popover-with-button.js
  styles/pages/user-and-team-page.styl
Labels: Ready to merge

#442 Superb guide: Remove EditableField and EditableWrappingField
  src/components/fields/project-domain-input.js
  src/components/fields/user-login-input.js
  src/components/fields/user-name-input.js
  src/components/global.styl
  src/components/inputs/text-input.js
  src/components/inputs/text-input.styl
  src/components/inputs/wrapping-text-input.js
  src/presenters/includes/edit-collection-name-and-url.js
  src/presenters/includes/editable-field.js
  src/presenters/includes/editable-wrapping-field.js
  src/presenters/pages/project.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/report-abuse-pop.js
  stories/index.js
  stories/inputs.js
  storybook-config/config.js
  styles/globals.styl
  styles/inputs.styl
Labels: Ready to merge

#455 Square salamander: use mask-image component on home page
  src/components/images/mask-image.js
  src/components/images/mask-image.styl
  src/presenters/featured-embed.js
  src/presenters/featured.js
  styles/includes/featured.styl
  styles/includes/zine-items.styl
Labels: Waiting on Reviews

#453 Scrawny puffin 1: fix search results storybook
  src/components/search-results/index.js
  src/components/search-results/search-results.styl
  src/presenters/pages/search.js
  stories/index.js
Labels: Waiting on Reviews

#449 Somber humor: fix `New Stuff` dialog positioning
  src/presenters/overlays/new-stuff.js
  styles/new-stuff.styl
  styles/overlays.styl
Labels: Waiting on Reviews

#454 Actually frill: storybooks for search form
  src/components/search-form/autocomplete.js
  src/components/search-form/autocomplete.styl
  src/components/search-form/index.js
  src/components/search-form/search-form.styl
  src/components/search-form/story.js
  src/presenters/header.js
  stories/data.js
  stories/index.js
  stories/util.js
Labels: Waiting on Reviews

#457 Wry rib: storybook for ProfileList
  src/components/collection/small-collection-item.js
  src/components/profile-list/index.js
  src/components/profile-list/profile-list.styl
  src/components/profile-list/story.js
  src/components/project/project-item.js
  src/components/search-form/story.js
  src/components/team/team-item.js
  src/presenters/featured-collections.js
  src/presenters/includes/profile.js
  src/presenters/includes/project-result-item.js
  src/presenters/note.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  stories/data.js
  stories/index.js
  stories/util.js
  storybook-config/config.js
Labels: Waiting on Reviews

#458 Good kangaroo: move components out of "blocks"
  src/components/search-result-cover-bar/index.js
  src/components/search-result-cover-bar/search-result-cover-bar.styl
  src/components/team/team-item.js
  src/components/thanks/index.js
  src/components/thanks/thanks.styl
  src/components/user/user-item.js
  src/presenters/includes/user-result-item.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  src/presenters/pop-overs/team-user-info-pop.js
  stories/index.js
Labels: Ready to merge

#456 Silly tanker: componentize MoreIdeas
  src/components/more-ideas/index.js
  src/components/more-ideas/more-ideas.styl
  src/presenters/more-ideas.js
  src/presenters/pages/category.js
  src/presenters/pages/index.js
  src/presenters/pages/questions.js
  src/presenters/pages/search.js
  stories/index.js
  styles/includes/more-ideas.styl
  styles/styles.styl
Labels: Ready to merge

#426 Nova chance: Check for cancelled oauth signin, refactor login to a functional component
  src/presenters/pages/login.js
  src/presenters/pages/router.js
Labels: Ready to merge

#461 Sweet blinker: Fix removing projects
  src/components/containers/projects-list.js
  src/presenters/pop-overs/project-options-pop.js
Labels: Ready to merge

#451 Profuse tea: Include ips in the request log
  server/api.js
  server/logger.js
  server/server.js
Labels: Waiting on Reviews

#465 Superb guide: Componentized EditableDescription as MarkdownInput
  src/components/fields/optimistic-markdown-input.js
  src/components/inputs/markdown-input.js
  src/components/inputs/markdown-input.styl
  src/components/inputs/text-area.js
  src/presenters/includes/auth-description.js
  src/presenters/includes/description-field.js
  src/presenters/includes/field-helpers.js
  src/presenters/note.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  stories/inputs.js
  styles/inputs.styl
  styles/note.styl
  styles/pages/collection.styl
  styles/pop-overs.styl
Labels: Ready to merge

#463 Time walleye: componentize team/user profile header
  src/components/profile-container/index.js
  src/components/profile-container/story.js
  src/components/profile-container/styles.styl
  src/presenters/includes/profile.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  stories/index.js
  styles/pages/project.styl
  styles/pages/user-and-team-page.styl
  styles/profile.styl
Labels: Ready to merge

#466 Tiny capybara: componentize DataLoader
  src/components/data-loader/index.js
  src/components/loader/index.js
  src/components/loader/loader.styl
  src/components/search-results/index.js
  src/presenters/collection-item.js
  src/presenters/collections-list.js
  src/presenters/deleted-projects.js
  src/presenters/featured-collections.js
  src/presenters/includes/loader.js
  src/presenters/includes/related-projects.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-analytics.js
  src/presenters/more-collections.js
  src/presenters/pages/category.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/team-or-user.js
  src/presenters/pages/team.js
  src/presenters/pop-overs/add-collection-project-pop.js
  src/presenters/pop-overs/add-project-to-collection-pop.js
  src/presenters/pop-overs/add-team-user-pop.js
  src/presenters/pop-overs/create-collection-pop.js
  src/presenters/pop-overs/create-team-pop.js
  src/presenters/pop-overs/delete-team-pop.js
  src/presenters/pop-overs/new-project-pop.js
  src/presenters/pop-overs/report-abuse-pop.js
  src/presenters/pop-overs/team-user-remove-pop.js
  src/presenters/recent-projects.js
  stories/index.js
Labels: Ready to merge

#459 Malachite animal: componentize link
  src/components/buttons/button.js
  src/components/link/index.js
  src/components/more-ideas/index.js
  src/components/profile-list/index.js
  src/components/project/project-item.js
  src/components/search-form/autocomplete.js
  src/components/user/user-item.js
  src/presenters/collection-item.js
  src/presenters/featured-collections.js
  src/presenters/featured-embed.js
  src/presenters/featured.js
  src/presenters/footer.js
  src/presenters/header.js
  src/presenters/includes/name-conflict.js
  src/presenters/includes/project-result-item.js
  src/presenters/includes/related-projects.js
  src/presenters/includes/team-analytics-project-details.js
  src/presenters/includes/team-elements.js
  src/presenters/includes/team-users.js
  src/presenters/more-collections.js
  src/presenters/overlays/new-stuff.js
  src/presenters/pages/index.js
  src/presenters/pop-overs/sign-in-pop.js
  src/presenters/pop-overs/team-user-info-pop.js
  src/presenters/pop-overs/user-options-pop.js
  src/presenters/question-item.js
  src/presenters/questions.js
  src/presenters/recent-projects.js
Labels: Under Review

#460 Intriguing adjustment: inline EntityPageProjects into User & Team pages
  src/presenters/entity-page-projects.js
  src/presenters/pages/team.js
  src/presenters/pages/user.js
Labels: Ready to merge

#446 Obtainable dew: Collection Item
  .glitch-assets
  src/components/badges/badge.js
  src/components/badges/badge.styl
  src/components/collection/collection-item-small.js
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/components/images/emoji.js
  src/components/project/project-item-small.js
  src/components/project/project-item.js
  src/components/project/project-item.styl
  src/components/search-results/index.js
  src/components/team/team-item.js
  src/components/team/team-item.styl
  src/components/user/user-item.js
  src/components/user/user-item.styl
  src/presenters/collections-list.js
  src/presenters/includes/included-in-collections.js
  stories/data.js
  stories/index.js
  styles/collections.styl
  styles/globals.styl
  styles/pages/user-and-team-page.styl
  styles/pop-overs.styl
  styles/user-and-team-item.styl
Labels: Ready to merge

#472 Hilarious pumpkin 1: componentize project profile and add avatar upload
  src/components/profile-container/index.js
  src/components/profile-container/styles.styl
  src/presenters/pages/project.js
  src/presenters/project-editor.js
  src/utils/assets.js
  styles/pages/project.styl
  styles/profile.styl
Labels: Ready to merge

#473 Superb guide: Get rid of old input presenters
  src/components/fields/collection-name-input.js
  src/components/fields/optimistic-wrapping-text-input.js
  src/components/inputs/text-input.js
  src/components/inputs/text-input.styl
  src/presenters/includes/edit-collection-name-and-url.js
  src/presenters/includes/field-helpers.js
  src/presenters/pages/collection.js
  src/presenters/pop-overs/edit-collection-color-pop.js
  stories/index.js
  stories/inputs.js
  styles/pop-overs.styl
Labels: Ready to merge

#452 Heady path: use personalized search credentials to remove private projects
  src/state/search.js
Labels: Waiting on Reviews

#477 Quixotic rocket: Use the rest api in current-user.js
  src/state/current-user.js
Labels: Ready to merge

#464 frosted-aquarius: Handle case where OAuth login fails due to no email provided
  src/presenters/pages/login.js
Labels: Ready to merge

#475 Hail locket: convert user & team pages to use css modules
  src/components/data-loader/index.js
  src/components/project/project-embed.styl
  src/presenters/pages/project.js
  src/presenters/pages/team.js
  src/presenters/pages/team.styl
  src/presenters/pages/user.js
  src/presenters/pages/user.styl
  styles/pages/user-and-team-page.styl
  styles/profile.styl
  styles/styles.styl
  styles/user-and-team-item.styl
  styles/users.styl
  webpack.config.js
Labels: Waiting on Reviews

#462 Peppered fahrenheit - Add Delete button to Project Pages
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/project-editor.js
  styles/buttons.styl
  styles/pop-overs.styl
Labels: Under Review

#468 Morning cockatoo: componentize footer
  .glitch-assets
  src/components/footer/footer.styl
  src/components/footer/index.js
  src/components/images/emoji.js
  src/presenters/footer.js
  src/presenters/layout.js
  stories/index.js
  styles/includes/footer.styl
  styles/styles.styl
Labels: Ready to merge

#478 Debonair cilantro: Deleted Projects component
  src/components/animation-container/animations.styl
  src/components/animation-container/index.js
  src/components/buttons/button.js
  src/components/buttons/button.styl
  src/components/buttons/transparent-button.js
  src/components/deleted-projects/deleted-projects.styl
  src/components/deleted-projects/index.js
  src/components/deleted-projects/story.js
  src/components/images/emoji.js
  src/components/images/emoji.styl
  src/presenters/pages/team.js
  src/presenters/pages/user.js
  stories/index.js
  styles/deleted-projects.styl
  styles/pages/user-and-team-page.styl
  styles/styles.styl
Labels: Ready to merge

#480 Necessary part: componentize questions
  src/components/questions/index.js
  src/components/questions/item.js
  src/components/questions/questions.styl
  src/components/questions/story.js
  src/presenters/pages/index.js
  src/presenters/pages/questions.js
  src/presenters/questions.js
  stories/index.js
  styles/includes/questions.styl
  styles/pages/questions.styl
  styles/styles.styl
Labels: Ready to merge

#487 Superb guide: Sort projects locally instead of using the api sort
  src/models/project.js
  src/state/current-user.js
Labels: Waiting on Reviews

#471 Husky calf: componentize header
  src/components/header/header.styl
  src/components/header/index.js
  src/components/header/logo.js
  src/components/header/story.js
  src/components/search-form/search-form.styl
  src/presenters/header.js
  src/presenters/includes/dev-toggles.js
  src/presenters/includes/logo.js
  src/presenters/includes/user-prefs.js
  src/presenters/layout.js
  src/presenters/overlays/new-stuff.js
  stories/index.js
  stories/util.js
  storybook-config/config.js
  styles/globals.styl
  styles/includes/header.styl
  styles/styles.styl
Labels: Ready to merge

#482 🎏: punycode-ify project, user, team names
  package.json
  server/api.js
  server/routes.js
  src/presenters/pages/router.js
Labels: Waiting on Reviews
