Repository glitchdotcom/Glitch-Community, pull requests merged in 2020-01, with the labels that each got.

#1144 Change annotation to note, for new v1 route
  src/curated/home.json
  src/state/collection.js
Labels: Ready to merge

#1146 Placid salto: use v0 routes for user pinned projects
  src/state/api.js
Labels: Waiting on Reviews

#1133 Update users api routes to v1
  src/state/api.js
  src/state/current-user.js
  src/state/user.js
Labels: Ready to merge

#1151 Create Feature Flag that is Protected by a Test Team Membership
  server/render.js
  server/routes.js
  src/client.js
  src/curated/home.json
  src/presenters/pages/secret.js
  src/server.js
  src/state/current-user.js
  src/state/dev-toggles.js
  src/state/globals.js
  src/state/rollouts.js
  src/utils/constants.js
  test/server/render.js
  test/state/rollouts.js
  views/index.ejs
Labels: Waiting on Reviews

#1153 separate projects into words and Title Case them
  src/presenters/pages/project.js
Labels: Waiting on Reviews

#1152 Nova chance: Add some extra documentation on RUNNING_ON vs RUNNING_LOCALLY
  README.md
  shared/constants.js
Labels: Waiting on Reviews

#1157 Update project api routes to v1
  src/state/api.js
Labels: Waiting on Reviews

#1156 verbena-moth: Add /pricing page
  src/components/footer/index.js
  src/presenters/pages/about/about-layout.js
  src/presenters/pages/about/pricing.js
  src/presenters/pages/about/pricing.styl
  src/presenters/pages/router.js
  src/presenters/pages/settings.js
Labels: Under Review

#1163 Put links to pricing behind feature flag
  src/components/footer/index.js
  src/curated/home.json
  src/presenters/pages/about/about-layout.js
Labels: Waiting on Reviews

#1162 Discovered seashore: Glitch PRO link in navigation
  src/components/glitch-pro-cta/index.js
  src/components/glitch-pro-cta/styles.styl
  src/components/header/header.styl
  src/components/header/index.js
  src/presenters/pages/about/pricing.js
Labels: Waiting on Reviews

#1164 Buttery vacation: clean up glitch pro data management
  src/app.js
  src/components/account-settings-overlay/subscription-settings.js
  src/components/glitch-pro-cta/index.js
  src/presenters/pages/about/pricing.js
  src/state/glitch-pro.js
  src/state/stripe.js
  src/state/subscription-status.js
Labels: Waiting on Reviews

#1159 only give admins add team user button
  src/components/team-users/index.js
  src/state/api.js
  src/state/current-user.js
  src/state/project-options.js
Labels: Ready to merge

#1166 Update collection page to handle extra memory
  src/components/collection/add-collection-project-pop.js
  src/components/collection/collection-projects-grid-view.js
  src/components/collection/collection-projects-grid-view.styl
  src/components/collection/container.js
  src/components/glitch-pro-cta/index.js
  src/components/images/avatar.js
  src/curated/home.json
  src/presenters/pages/collection.js
  test/components/collection/add-collection-project-pop.js
  test/components/collection/collection-projects-grid-view.js
  test/components/collection/container.js
Labels: Waiting on Reviews

#1168 add filteredTag util to avoid passing custom props
  src/components/glitch-pro-cta/index.js
  src/components/header/index.js
  src/components/notification/index.js
  src/components/recent-projects/index.js
  src/components/team/team-item.js
  src/components/user-options-pop/index.js
  src/presenters/pages/about/index.js
  src/presenters/pages/create.js
  src/presenters/pages/home-v2/banner.js
  src/presenters/pages/home-v2/index.js
  src/presenters/pages/team.js
  src/utils/filteredTag.js
Labels: Waiting on Reviews

#1170 Abiding dash: settings page improvements
  .glitch-assets
  src/components/account-settings-overlay/settings-tabs-container/index.js
  src/components/account-settings-overlay/settings-tabs-container/styles.styl
  src/components/account-settings-overlay/subscription-settings.js
  src/components/glitch-pro-cta/index.js
  src/presenters/pages/router.js
  src/presenters/pages/settings.js
  src/presenters/pages/settings.styl
  test/components/settings-tabs.js
Labels: Under Review

#1149 Quixotic rocket: Only send the experiment viewed event if the experiment is active
  .glitch-assets
  src/curated/pupdates.json
  src/state/rollouts.js
  src/utils/constants.js
Labels: Ready to merge

#1148 various dart: completes account closing work
  src/components/delete-account/delete-account-modal.js
  src/components/project/project-embed.js
  src/components/project/project-options-pop.js
  src/components/team-users/team-user-info.js
  src/presenters/pages/delete.js
  src/presenters/pages/settings.js
  src/state/api.js
Labels: Waiting on Reviews

#1171 Show star in collections list when it's an protected collection
  src/components/collection/collection-item.js
  src/components/collection/collection-item.styl
  src/state/collection.js
  test/components/collection/collection-item.js
  test/helpers/mockContext.js
Labels: Waiting on Reviews

#1177 add HSTS
  package.json
  server/server.js
Labels: Ready to merge

#1174 separate and Title Case team and collection page titles
  src/hooks/use-title-formatter.js
  src/presenters/pages/collection.js
  src/presenters/pages/project.js
  src/presenters/pages/team.js
Labels: Ready to merge

#1173 moves pup into aside
  src/components/new-stuff/new-stuff-prompt.js
Labels: Ready to merge

#1172 remove X from all search boxes
  src/components/global.styl
Labels: Ready to merge

#1139 Superb guide: If there's an error loading ssr code, dump the cache and try again on the next request
  server/render.js
Labels: Ready to merge

#1180 load empty script if pufferfish isn't enabled
  src/state/glitch-pro.js
Labels: Waiting on Reviews

#1175 Quixotic rocket: Get rid of the lodash module replacement plugin to fix an optimizely error
  package.json
  server/optimizely.js
  server/routes.js
  shrinkwrap.yaml
  src/client.js
  views/index.ejs
  webpack.config.js
Labels: Waiting on Reviews
